define({
  "_widgetLabel": "Piirrä",
  "selectDrawMode": "Valitse piirustustapa",
  "clear": "Tyhjennä",
  "point": "Piste",
  "line": "Viiva",
  "polyline": "Taiteviiva",
  "freehandPolyline": "Viivan piirto vapaalla kädellä",
  "triangle": "Kolmio",
  "extent": "Kirjekuori",
  "circle": "Ympyrä",
  "ellipse": "Ellipsi",
  "polygon": "Alue",
  "freehandPolygon": "Alueen piirto vapaalla kädellä",
  "text": "Teksti",
  "style": "Tyyli",
  "alpha": "Läpinäkyvyys",
  "width": "Leveys",
  "size": "Koko",
  "color": "Väri",
  "markerColor": "Merkinnän väri",
  "outlineColor": "Reunaviivan väri",
  "lineColor": "Viivan väri",
  "fillColor": "Täyttöväri",
  "showMeasurements": "Näytä mittaukset",
  "areaUnits": "Pinta-alayksiköt",
  "distanceUnits": "Etäisyyden yksiköt",
  "kilometers": "Kilometriä",
  "miles": "Mailia",
  "meters": "Metriä",
  "feet": "Jalkaa",
  "yards": "Jaardia",
  "nauticalmiles": "Meripeninkulmaa",
  "squareKilometers": "Neliökilometriä",
  "squareMiles": "Neliömailia",
  "acres": "Eekkeriä",
  "hectares": "Hehtaaria",
  "squareMeters": "Neliömetriä",
  "squareFeet": "Neliöjalkaa",
  "squareYards": "Neliöjaardia",
  "undo": "Kumoa",
  "redo": "Tee uudelleen",
  "results": "Tulokset",
  "points": "Pisteitä",
  "lines": "Viivoja",
  "areas": "Alueet"
});