define({
  "showArcgisBasemaps": "包括 Portal 的底图",
  "add": "单击以添加新底图",
  "edit": "属性",
  "titlePH": "底图标题",
  "thumbnailHint": "单击图像以更新",
  "urlPH": "图层 URL",
  "addlayer": "添加底图",
  "warning": "输入不正确",
  "save": "返回并保存",
  "back": "返回并取消",
  "addUrl": "添加 URL",
  "autoCheck": "自动检查",
  "checking": "正在检查...",
  "result": "已成功保存",
  "spError": "添加到图库的所有底图必须具有相同的空间参考。",
  "invalidTitle1": "底图 '",
  "invalidTitle2": "' 已存在。请选择其它标题。",
  "invalidBasemapUrl1": "此类型的图层不能用作底图。",
  "invalidBasemapUrl2": "您正在添加的底图与当前地图拥有不同的空间参考。",
  "addBaselayer": "添加底图图层",
  "repectOnline": "始终与组织的底图库设置同步",
  "customBasemap": "配置自定义底图",
  "basemapTips": "单击“${import}”或“${createNew}”添加底图。",
  "importBasemap": "导入",
  "createBasemap": "新建",
  "importTitle": "导入底图",
  "createTitle": "新建底图",
  "selectGroupTip": "选择可将 web 地图用作底图的群组。",
  "noBasemaps": "无底图。",
  "defaultGroup": "Esri 默认值",
  "defaultOrgGroup": "组织默认值",
  "warningTitle": "警告",
  "confirmDelete": "是否要删除所选底图?",
  "noBasemapAvailable": "无可用底图，因为所有底图的空间参考或切片方案与当前地图的均不相同。"
});