define({
  "_widgetLabel": "Ģeodatu apstrāde",
  "_featureAction_ReceiveFeatureSet": "Iestatīt kā ievadi šim: ",
  "requiredInfo": "ir obligāts.",
  "drawnOnMap": "Rezultāts tiek zīmēts kartē.",
  "noToolConfig": "Nav pieejams neviens iepriekš konfigurēts ģeodatu apstrādes uzdevums.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Augšupielādējiet failu",
  "selectFileToUpload": "Atlasiet failu...",
  "rasterFormat": "Rastra datu formāts",
  "noFileSelected": "Nav atlasīts fails!",
  "uploadSuccess": "Faila augšupielāde veiksmīga!",
  "showLayerContent": "Rādīt slāņa saturu",
  "invalidUrl": "Nederīgs elementu pakalpojuma URL",
  "urlPlaceholder": "elementu kopas URL",
  "addShapefile": "Pievienot Shape failu",
  "generateShapefileError": "Ģenerēt Shape faila kļūdu; pārbaudiet: ",
  "cleared": "Rezultāts ir notīrīts.",
  "enlargeView": "Palielināt skatu",
  "exportOutput": "Eksportēt",
  "emptyResult": "Rezultāts ir tukšs.",
  "useSelectedFeatureset": "Izmantot rezultātā iegūto(-s) elementu(-s).",
  "closeSelectedFeatureset": "Notīrīt un izmantot konfigurētās ievades opciju."
});