define({
  "_widgetLabel": "Imprimir",
  "title": "Título do mapa",
  "format": "Formato",
  "layout": "Layout",
  "settings": "Avançado",
  "labels": "Rótulos",
  "showLabels": "Exibir rótulos",
  "mapScaleExtent": "Escala/extensão do mapa",
  "preserve": "Preservar",
  "mapScale": "escala do mapa",
  "mapExtent": "extensão do mapa",
  "forceScale": "Forçar escala",
  "getCurrentScale": "atual",
  "mapMetadata": "Metadados do layout",
  "author": "Autor",
  "copyright": "Copyright",
  "fullLayoutOptions": "Opções completas do layout",
  "scaleBarUnitsMetric": "Unidades de barra de escala métricas",
  "scaleBarUnitsNonMetric": "Unidades de barra de escala não-métricas",
  "unitsMiles": "Milhas",
  "unitsKilometers": "Quilómetros",
  "unitsMeters": "Metros",
  "unitsFeet": "Pés",
  "unitsYards": "Jardas",
  "unitsNauticalMiles": "Milhas Náuticas",
  "lncludeLegend": "Incluir legenda",
  "printQualityOptions": "Qualidade de impressão",
  "dpi": "DPI",
  "mapOnlyOptions": "Tamanho MAP_ONLY",
  "width": "Largura (px)",
  "height": "Altura (px)",
  "print": "Imprimir",
  "clearList": "Limpar impressões",
  "creatingPrint": "A criar impressão",
  "printError": "Erro, tente novamente"
});