define({
  "taskUrl": "Tehtävän URL-osoite",
  "serviceURLPlaceholder": "Syötä geoprosessointitehtävän URL-osoite",
  "layerOrder": "Karttatasojen järjestys",
  "defaultValue": "Oletusarvo",
  "inputFeatureBy": "Lähtöaineiston kohde",
  "renderer": "Renderöinti",
  "displayType": "Näyttötyyppi",
  "helpUrl": "Ohjeen URL-osoite",
  "useResultMapService": "Näytä tulos karttapalvelussa",
  "drawOnMap": "Interaktiivinen piirtäminen kartalla",
  "selectLayer": "Karttatason valitseminen kartasta",
  "shareResults": "Lisää tulos toiminnalliseksi karttatasoksi",
  "setTask": "Aseta",
  "setTaskTitle": "Määritä geoprosessointitehtävä",
  "enablePopup": "Ota ponnahdusikkunat käyttöön",
  "unSupportGeometryType": "Renderöintiä ei voi määrittää tuntemattoman geometriatyypin vuoksi.",
  "useUrlForGPInput": "URL-osoite",
  "useUploadForGPInput": "Lähetä tiedosto",
  "selectFileToUpload": "Valitse tiedosto...",
  "rasterFormat": "Rasteriaineiston muoto",
  "noFileSelected": "Yhtään tiedostoa ei ole valittu.",
  "uploadSuccess": "Tiedoston lataus onnistui.",
  "showLayerContent": "Näytä karttatason sisältö",
  "urlPlaceholder": "kohderyhmän URL-osoite",
  "useShapefile": "Käytä shapefile-tiedostoa paikallisessa tiedostojärjestelmässä",
  "allowToExport": "Salli tulosten vienti",
  "useDynamicSchema": "Tulosaineistossa voi olla toinen skeema. Käytä dynaamista skeemaa ennalta määritetyn skeeman sijasta."
});