define({
  "taskUrl": "عنوان URL للمهمة",
  "serviceURLPlaceholder": "الرجاء إدخال عنوان URL لمهمة المعالجة الجغرافية",
  "layerOrder": "ترتيب الطبقة",
  "defaultValue": "القيمة الافتراضية",
  "inputFeatureBy": "إدخال المعلم بواسطة",
  "renderer": "العارض",
  "displayType": "نوع العرض",
  "helpUrl": "عنوان URL للتعليمات",
  "useResultMapService": "عرض النتائج مع خدمة خريطة",
  "drawOnMap": "الرسم التفاعلي على الخريطة",
  "selectLayer": "تحديد الطبقة من الخريطة",
  "shareResults": "إضافة النتيجة كطبقة تشغيلية",
  "setTask": "تعيين",
  "setTaskTitle": "تعيين مهمة GP",
  "enablePopup": "تمكين عنصر منبثق",
  "unSupportGeometryType": "يتعذر تعيين المُقدّم نظرًا لأن نوع الشكل الهندسي غير معروف.",
  "useUrlForGPInput": "عنوان URL",
  "useUploadForGPInput": "تحميل الملف",
  "selectFileToUpload": "حدد ملف...",
  "rasterFormat": "تنسيق البيانات النقطية",
  "noFileSelected": "لم يتم تحديد أي ملف!",
  "uploadSuccess": "تم تحميل الملف بنجاح!",
  "showLayerContent": "عرض محتوى الطبقة",
  "urlPlaceholder": "عنوان URL لمجموعة المعالم",
  "useShapefile": "استخدم ملف الشكل في نظام ملفات محلي",
  "allowToExport": "السماح بتصدير النتائج",
  "useDynamicSchema": "قد يحتوي الناتج على مخطط مختلف، استخدم مخططًا ديناميكيًا بدلاً من المُعرّف مُسبقًا.",
  "useCurrentMapExtent": "استخدم نطاق الخريطة الحالي",
  "ignoreOutput": "تجاهل هذا الناتج",
  "turnOffOutput": "إيقاف تشغيل هذه الطبقة افتراضيًا"
});