define({
  "showArcgisBasemaps": "Includeţi hărţi fundal ale portalului",
  "add": "Faceţi clic pentru a adăuga o hartă fundal nouă",
  "edit": "Proprietăţi",
  "titlePH": "Titlu hartă fundal",
  "thumbnailHint": "Faceţi clic pe imagine pentru a o actualiza",
  "urlPH": "URL strat tematic",
  "addlayer": "Adăugare hartă fundal",
  "warning": "Intrare incorectă",
  "save": "Revenire şi salvare",
  "back": "Revenire şi anulare",
  "addUrl": "Adăugare URL",
  "autoCheck": "Verificare automată",
  "checking": "În curs de verificare...",
  "result": "Salvare reuşită",
  "spError": "Toate hărţile fundal adăugate în galerie trebuie să aibă aceeaşi referinţă spaţială.",
  "invalidTitle1": "Există deja o hartă fundal „„",
  "invalidTitle2": "””. Selectaţi alt nume.",
  "invalidBasemapUrl1": "Acest tip de strat tematic nu poate fi utilizat drept hartă fundal.",
  "invalidBasemapUrl2": "Harta fundal pe care o adăugaţi are o referinţă spaţială diferită în comparaţie cu harta curentă.",
  "addBaselayer": "Adăugare strat tematic de hartă fundal",
  "repectOnline": "Întotdeauna sincronizează cu setarea Galeriei de hărţi fundal a organizaţiei",
  "customBasemap": "Configurare hărţi fundal particularizate",
  "basemapTips": "Faceţi clic pe \"${import}\" sau \"${createNew}\" pentru a adăuga hărţi fundal.",
  "importBasemap": "Import",
  "createBasemap": "Creare nouă",
  "importTitle": "Import hărţi fundal",
  "createTitle": "Hartă fundal nouă",
  "selectGroupTip": "Selectaţi un grup ale cărui hărţi web pot fi utilizate ca hărţi fundal.",
  "noBasemaps": "Nicio hartă fundal.",
  "defaultGroup": "Esri implicit",
  "defaultOrgGroup": "Valoare implicită organizaţie",
  "warningTitle": "Avertisment",
  "confirmDelete": "Doriţi să ştergeţi hărţile fundal selectate?",
  "noBasemapAvailable": "Nu există hărţi fundal disponibile, deoarece toate hărţile fundal au o referinţă spaţială sau o schemă de acoperire diferită în comparaţie cu harta curentă."
});