define({
  "_widgetLabel": "Geoduomenų apdorojimas",
  "_featureAction_ReceiveFeatureSet": "Nustatyti kaip įvestį ",
  "requiredInfo": "būtina.",
  "drawnOnMap": "Rezultatas nupieštas žemėlapyje.",
  "noToolConfig": "Iš anksto sukonfigūruotos geoduomenų apdorojimo užduoties nėra.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Įkelti failą",
  "selectFileToUpload": "Pasirinkite failą...",
  "rasterFormat": "Rastrinių duomenų formatas",
  "noFileSelected": "Nepasirinktas joks failas!",
  "uploadSuccess": "Failas įkeltas sėkmingai!",
  "showLayerContent": "Rodyti sluoksnio turinį",
  "invalidUrl": "Netinkamas elementų paslaugos url",
  "urlPlaceholder": "elementui nustatytas URL",
  "addShapefile": "Įtraukti Shape failą",
  "generateShapefileError": "Sugeneruokite Shape failo klaidą, žr.: ",
  "cleared": "Rezultatai išvalyti:",
  "enlargeView": "Padidinti vaizdą",
  "exportOutput": "Eksportuoti",
  "emptyResult": "Rezultato nėra.",
  "useSelectedFeatureset": "Naudoti rezultato elementą (-us).",
  "closeSelectedFeatureset": "Valyti ir naudoti sukonfigūruotą įvesties parinktį.",
  "currentMapExtent": "Esama žemėlapio aprėptis"
});