define({
  "addDistance": "Adicionar unidade de comprimento",
  "addArea": "Adicionar unidade de área",
  "label": "Rótulo",
  "abbr": "Abreviação",
  "conversion": "Conversão",
  "actions": "Ações",
  "areaUnits": "Unidades de área",
  "distanceUnits": "Unidades de comprimento",
  "kilometers": "Quilômetros",
  "miles": "Milhas",
  "meters": "Metros",
  "feet": "Pés",
  "yards": "Jardas",
  "nauticalmiles": "Milhas náuticas",
  "squareKilometers": "Quilómetros quadrados",
  "squareMiles": "Milhas quadradas",
  "acres": "Acres",
  "hectares": "Hectares",
  "squareMeters": "Metros quadrados",
  "squareFeet": "Pés quadrados",
  "squareYards": "Jardas quadradas",
  "distance": "Distâncias",
  "area": "Áreas",
  "kilometersAbbreviation": "km",
  "milesAbbreviation": "milhas",
  "metersAbbreviation": "m",
  "feetAbbreviation": "pés",
  "yardsAbbreviation": "jardas",
  "nauticalmilesAbbreviation": "nm",
  "squareKilometersAbbreviation": "km2",
  "squareMilesAbbreviation": "milhas2",
  "acresAbbreviation": "ac",
  "hectaresAbbreviation": "ha",
  "squareMetersAbbreviation": "m2",
  "squareFeetAbbreviation": "pés2",
  "squareYardsAbbreviation": "jardas2",
  "defineUnits": "Definir unidades de medição.",
  "operationalLayer": "Adicionar desenho como uma camada operacional do mapa."
});