define({
  "_widgetLabel": "Рисование",
  "selectDrawMode": "Выбрать режим рисования",
  "clear": "Очистить",
  "point": "Точка",
  "line": "Линия",
  "polyline": "Линия",
  "freehandPolyline": "Произвольная полилиния",
  "triangle": "Треугольник",
  "extent": "Конверт",
  "circle": "Круг",
  "ellipse": "Эллипс",
  "polygon": "Полигон",
  "freehandPolygon": "Произвольный полигон",
  "text": "Текст",
  "style": "Стиль",
  "alpha": "Прозрачность",
  "width": "Ширина",
  "size": "Размер",
  "color": "Цвет",
  "markerColor": "Цвет маркера",
  "outlineColor": "Цвет контура",
  "lineColor": "Цвет линии",
  "fillColor": "Цвет заливки",
  "showMeasurements": "Показать измерения",
  "areaUnits": "Единицы площади",
  "distanceUnits": "Единицы расстояния",
  "kilometers": "Километры",
  "miles": "Мили",
  "meters": "Метры",
  "feet": "Футы",
  "yards": "Ярды",
  "nauticalmiles": "Морские мили",
  "squareKilometers": "Квадратные километры",
  "squareMiles": "Квадратные мили",
  "acres": "Акры",
  "hectares": "гектары",
  "squareMeters": "Квадратные метры",
  "squareFeet": "Квадратные футы",
  "squareYards": "Квадратные ярды",
  "undo": "Отменить",
  "redo": "Повторить",
  "results": "Результаты",
  "points": "Точки",
  "lines": "Линии",
  "areas": "Области"
});