define({
  "_widgetLabel": "Coğrafi İşlemler",
  "_featureAction_ReceiveFeatureSet": "Şunun girdisi olarak ayarla: ",
  "requiredInfo": "gereklidir.",
  "drawnOnMap": "Sonuç haritada çizilidir.",
  "noToolConfig": "Önceden yapılandırılmış coğrafi işlem görevi yok.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Dosya yükle",
  "selectFileToUpload": "Dosya seç...",
  "rasterFormat": "Raster veri formatı",
  "noFileSelected": "Dosya seçilmedi!",
  "uploadSuccess": "Dosya yükleme başarılı!",
  "showLayerContent": "Katman içeriğini göster",
  "invalidUrl": "Geçersiz detay hizmeti url'si",
  "urlPlaceholder": "detay kümesi URL'si",
  "addShapefile": "Shapefile Ekle",
  "generateShapefileError": "Shapefile hatası oluştu, kontrol edin: ",
  "cleared": "Sonuç silindi.",
  "enlargeView": "Görünümü genişlet",
  "exportOutput": "Dışa Aktar",
  "emptyResult": "Sonuç boş.",
  "useSelectedFeatureset": "Sonuçta ortaya çıkan detayları kullan.",
  "closeSelectedFeatureset": "Temizle ve yapılandırılmış girdi seçeneğini kullan."
});