define({
  "_widgetLabel": "Natisni",
  "title": "Naslov karte",
  "format": "Format",
  "layout": "Postavitev",
  "settings": "Napredno",
  "labels": "Napisi",
  "showLabels": "Pokaži napise",
  "mapScaleExtent": "Obseg karte",
  "preserve": "Ohrani",
  "mapScale": "merilo karte",
  "mapExtent": "obseg karte",
  "forceScale": "Vsili merilo",
  "getCurrentScale": "trenutno",
  "mapMetadata": "Meta podatki postavitve",
  "author": "Avtor",
  "copyright": "Avtorske pravice",
  "fullLayoutOptions": "Možnosti celotne postavitve",
  "scaleBarUnitsMetric": "Metrične enote grafičnega merila",
  "scaleBarUnitsNonMetric": "Nemetrične enote grafičnega merila",
  "unitsMiles": "Milje",
  "unitsKilometers": "Kilometri",
  "unitsMeters": "Metri",
  "unitsFeet": "Čevlji",
  "unitsYards": "Jardi",
  "unitsNauticalMiles": "Morske milje",
  "lncludeLegend": "Vključi legendo",
  "printQualityOptions": "Kakovost tiskanja",
  "dpi": "DPI",
  "mapOnlyOptions": "Velikost MAP_ONLY",
  "width": "Širina (v px)",
  "height": "Višina (v px)",
  "print": "Natisni",
  "clearList": "Odstrani tisk",
  "creatingPrint": "Ustvarjanje tiska",
  "printError": "Napaka, poskusite znova"
});