define({
  "showArcgisBasemaps": "Vključi temeljne karte Portala",
  "add": "Kliknite za dodajanje nove temeljne karte",
  "edit": "Lastnosti",
  "titlePH": "Naslov temeljne karte",
  "thumbnailHint": "Kliknite sliko za posodobitev",
  "urlPH": "URL sloja",
  "addlayer": "Dodaj temeljno karto",
  "warning": "Nepravilen vnos",
  "save": "Nazaj in shrani",
  "back": "Nazaj in prekliči",
  "addUrl": "Dodaj URL",
  "autoCheck": "Samodejno preverjanje",
  "checking": "Preverjanje...",
  "result": "Uspešno shranjeno",
  "spError": "Vse temeljne karte, dodane v galerijo, morajo imeti isti koordinatni sistem.",
  "invalidTitle1": "Temeljna karta »",
  "invalidTitle2": "« že obstaja. Izberite drugo ime.",
  "invalidBasemapUrl1": "Ta tip sloja ne more biti uporabljen kot temeljna karta.",
  "invalidBasemapUrl2": "Temeljna karta, ki jo dodajate, ima drugačen koordinatni sistem kot trenutna karta.",
  "addBaselayer": "Dodaj sloj temeljne karte",
  "repectOnline": "Vedno sinhroniziraj z nastavitvijo galerije temeljnih kart organizacije",
  "customBasemap": "Konfiguriraj temeljne karte po meri",
  "basemapTips": "Za dodajanje temeljnih kart kliknite »${import}« ali »${createNew}«.",
  "importBasemap": "Uvozi",
  "createBasemap": "Ustvari novo",
  "importTitle": "Uvozi temeljne karte",
  "createTitle": "Nova temeljna karta",
  "selectGroupTip": "Izberite skupino, katere spletne karte so lahko uporabljene kot temeljne karte.",
  "noBasemaps": "Ni temeljnih kart.",
  "defaultGroup": "Privzeto Esri",
  "defaultOrgGroup": "Privzeto organizacije",
  "warningTitle": "Opozorilo",
  "confirmDelete": "Želite izbrisati izbrane temeljne karte?",
  "noBasemapAvailable": "Ni razpoložljivih temeljnih kart, ker imajo vse temeljne karte drugačen koordinatni sistem ali ploščično shemo kot trenutna karta."
});