define({
  "_widgetLabel": "Geoverarbeitung",
  "_featureAction_ReceiveFeatureSet": "Festlegen als Eingabe von ",
  "requiredInfo": "ist erforderlich.",
  "drawnOnMap": "Das Ergebnis wird auf der Karte dargestellt.",
  "noToolConfig": "Kein vorkonfigurierter Geoverarbeitungs-Task verfügbar.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Datei hochladen",
  "selectFileToUpload": "Datei auswählen...",
  "rasterFormat": "Raster-Datenformat",
  "noFileSelected": "Keine Datei ausgewählt!",
  "uploadSuccess": "Datei wurde erfolgreich hochgeladen!",
  "showLayerContent": "Layer-Inhalt anzeigen",
  "invalidUrl": "Ungültige Feature-Service-URL",
  "urlPlaceholder": "Feature-Set-URL",
  "addShapefile": "Shapefile hinzufügen",
  "generateShapefileError": "Fehler beim Erstellen der Shapefile; überprüfen Sie Folgendes: ",
  "cleared": "Das Ergebnis wurde gelöscht.",
  "enlargeView": "Ansicht vergrößern",
  "exportOutput": "Exportieren",
  "emptyResult": "Das Ergebnis ist leer.",
  "useSelectedFeatureset": "Verwenden Sie das/die resultierende(n) Feature(s).",
  "closeSelectedFeatureset": "Löschen und verwenden Sie die konfigurierte Eingabe-Option."
});