define({
  "_widgetLabel": "प्रिंट करें",
  "title": "मैप का शीर्षक",
  "format": "फ़ॉर्मेट या प्रारूप",
  "layout": "रूपरेखा",
  "settings": "उन्नत",
  "labels": "लेबल्स",
  "showLabels": "लेबल दिखाएं",
  "mapScaleExtent": "मानचित्र स्केल/सीमा",
  "preserve": "रक्षित",
  "mapScale": "मानचित्र स्केल",
  "mapExtent": "मानचित्र सीमा",
  "forceScale": "फ़ोर्स स्केल",
  "getCurrentScale": "वर्तमान",
  "mapMetadata": "रूपरेखा मेटाडाटा",
  "author": "लेखक",
  "copyright": "कॉपीराईट",
  "fullLayoutOptions": "पूर्ण रूपरेखा विकल्प",
  "scaleBarUnitsMetric": "स्केल बार की इकाई मीट्रिक",
  "scaleBarUnitsNonMetric": "स्केल बार की इकाई गैर-मेट्रिक",
  "unitsMiles": "मील",
  "unitsKilometers": "किलोमीटर",
  "unitsMeters": "मीटर",
  "unitsFeet": "फ़ीट",
  "unitsYards": "गज",
  "unitsNauticalMiles": "समुद्री मील",
  "lncludeLegend": "लीजेंड शामिल करें",
  "printQualityOptions": "प्रिंट गुणवत्ता",
  "dpi": "DPI",
  "mapOnlyOptions": "MAP_ONLY आकार",
  "width": "चौड़ाई (px)",
  "height": "ऊंचाई (px)",
  "print": "प्रिंट करें",
  "clearList": "साफ प्रिंट",
  "creatingPrint": "प्रिंट बनाना",
  "printError": "त्रुटि, फिर से कोशिश करें"
});