define({
  "_widgetLabel": "Štampaj",
  "title": "Naslov mape",
  "format": "Format",
  "layout": "Raspored",
  "settings": "Napredno",
  "labels": "Oznake",
  "showLabels": "Prikaži oznake",
  "mapScaleExtent": "Razmera/obuhvat mape",
  "preserve": "Očuvaj",
  "mapScale": "razmera mape",
  "mapExtent": "obuhvat mape",
  "forceScale": "Nametni razmeru",
  "getCurrentScale": "trenutno",
  "mapMetadata": "Metapodaci rasporeda",
  "author": "Autor",
  "copyright": "Autorsko pravo",
  "fullLayoutOptions": "Opcije punog rasporeda",
  "scaleBarUnitsMetric": "Metričke jedinice trake razmernika",
  "scaleBarUnitsNonMetric": "Nemetričke jedinice trake razmernika",
  "unitsMiles": "Milje",
  "unitsKilometers": "Kilometri",
  "unitsMeters": "Metri",
  "unitsFeet": "Stope",
  "unitsYards": "Jardi",
  "unitsNauticalMiles": "Nautičke milje",
  "lncludeLegend": "Uključi legendu",
  "printQualityOptions": "Kvalitet štampe",
  "dpi": "DPI",
  "mapOnlyOptions": "MAP_ONLY veličina",
  "width": "Širina (px)",
  "height": "Visina",
  "print": "Štampaj",
  "clearList": "Obriši štampu",
  "creatingPrint": "Kreiranje štampe",
  "printError": "Greška, pokušajte kasnije"
});