# Created on: 2016-06-24 12:05:46.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: DrawSystems <Feature_Set> <Output_XY_Systems>
# Description:
# ---------------------------------------------------------------------------

# Import all necessary module dependencies
import arcpy
import os
import sys

arcpy.env.overwriteOutput = True
arcpy.env.outputCoordinateSystem = arcpy.SpatialReference(3857)

def UploadSystems():

    # Get the value of the input parameter
    inTable = arcpy.GetParameterAsText(0)
    X_field = arcpy.GetParameterAsText(1)
    Y_field = arcpy.GetParameterAsText(2)

    # Local variable:
    out_layer = "Systems_lyr"
    arcpy.SetProgressorLabel('Creating System Components ...')
    arcpy.AddMessage('Creating System Components ...')

    if inTable or inTable != "#":

        try:
            # Process: Make XY Event Layer (temporary)
            arcpy.MakeXYEventLayer_management(table=inTable,
                                              in_x_field=X_field, in_y_field=Y_field,
                                              out_layer=out_layer)

            # Process: Create Feature Class from Feature Layer
            outSystems_fc = os.path.join(arcpy.env.scratchGDB, "Systems")
            arcpy.CopyFeatures_management(out_layer, outSystems_fc)

            # Process: Add XY Coordinates
            arcpy.SetProgressorLabel('Adding XY Coordinates ...')
            arcpy.AddMessage('Adding XY Coordinates ...')
            # Process: Add Coordinates
            arcpy.AddXY_management(outSystems_fc)

        except Exception:
            e = sys.exc_info()[1]
            arcpy.AddError('An error occurred: {}'.format(e.args[0]))
    else:
        arcpy.AddError('No Features Uploaded to the Map!')

    #### Set Parameters ####
    arcpy.SetParameterAsText(3, outSystems_fc)
    arcpy.ResetProgressor()

if __name__ == '__main__':
    UploadSystems()