define({
  "taskUrl": "작업 URL",
  "serviceURLPlaceholder": "지오프로세싱 작업 URL을 입력하세요.",
  "layerOrder": "레이어 순서",
  "defaultValue": "기본값",
  "inputFeatureBy": "입력 피처 작성자",
  "renderer": "렌더러",
  "displayType": "표시 유형",
  "helpUrl": "도움말 URL",
  "useResultMapService": "맵 서비스로 결과 보기",
  "drawOnMap": "맵에 대화식으로 그리기",
  "selectLayer": "맵에서 레이어 선택",
  "shareResults": "결과를 운영 레이어로 추가",
  "setTask": "설정",
  "setTaskTitle": "GP 작업 설정",
  "enablePopup": "팝업 사용",
  "unSupportGeometryType": "알 수 없는 지오메트리 유형으로 인해 렌더러를 설정할 수 없습니다.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "파일 업로드",
  "selectFileToUpload": "파일 선택...",
  "rasterFormat": "래스터 데이터 형식",
  "noFileSelected": "선택한 파일 없음",
  "uploadSuccess": "파일 업로드 완료",
  "showLayerContent": "레이어 콘텐츠 보기",
  "urlPlaceholder": "기능 모음 URL",
  "useShapefile": "로컬 파일 시스템에서 쉐이프파일 사용",
  "allowToExport": "결과 내보내기 허용",
  "useDynamicSchema": "결과에 다른 스키마가 있을 수 있습니다. 미리 정의된 스키마 대신 동적 스키마를 사용합니다.",
  "useCurrentMapExtent": "현재 맵 범위 사용",
  "ignoreOutput": "이 결과 무시",
  "turnOffOutput": "기본 설정에 따라 이 레이어 끄기"
});