define({
  "taskUrl": "Ülesande URL",
  "serviceURLPlaceholder": "Sisestage geotöötluse toimingu URL",
  "layerOrder": "Kihi järjestus",
  "defaultValue": "Vaikeväärtus",
  "inputFeatureBy": "Sisendobjektid vastavalt",
  "renderer": "Renderdaja",
  "displayType": "Kuva tüüp",
  "helpUrl": "Abi URL",
  "useResultMapService": "Tulemuse kuvamine kaarditeenusega",
  "drawOnMap": "Interaktiivselt kaardile joonistamine",
  "selectLayer": "Kihi valimine kaardilt",
  "shareResults": "Lisa tulemus töökihina",
  "setTask": "Määra",
  "setTaskTitle": "Määra GT toiming",
  "enablePopup": "Luba hüpikaken",
  "unSupportGeometryType": "Renderdajat ei saa määrata, kuna geomeetria tüüp on tundmatu.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Faili üleslaadimine",
  "selectFileToUpload": "Vali fail...",
  "rasterFormat": "Rasterandmete formaat",
  "noFileSelected": "Ühtegi faili pole valitud!",
  "uploadSuccess": "Faili üleslaadimine oli edukas!",
  "showLayerContent": "Kuva kihi sisu",
  "urlPlaceholder": "objektikomplekti URL",
  "useShapefile": "Kasuta Shape-faili kohalikus failisüsteemis",
  "allowToExport": "Luba tulemused eksportida",
  "useDynamicSchema": "Väljundil võib olla erinev skeem, kasutage eelmääratletud skeemi asemel dünaamilist skeemi.",
  "useCurrentMapExtent": "Kasuta praeguse kaardi ulatust",
  "ignoreOutput": "Eira seda väljundit",
  "turnOffOutput": "Lülita see kiht vaikimisi välja"
});