define({
  "showArcgisBasemaps": "Includi mappe di base del portale",
  "add": "Fare clic per aggiungere una nuova mappa di base",
  "edit": "Proprietà",
  "titlePH": "Titolo mappa di base",
  "thumbnailHint": "Fare clic sull'immagine per aggiornare",
  "urlPH": "URL layer",
  "addlayer": "Aggiungi mappa di base",
  "warning": "Input errato",
  "save": "Torna e salva",
  "back": "Torna e annulla",
  "addUrl": "Aggiungi URL",
  "autoCheck": "Verifica automatica",
  "checking": "Verifica in corso...",
  "result": "Salvataggio riuscito",
  "spError": "Tutte le mappe di base aggiunte alla galleria devono avere lo stesso riferimento spaziale.",
  "invalidTitle1": "Una mappa di base '",
  "invalidTitle2": "' esiste già. Scegliere un altro titolo.",
  "invalidBasemapUrl1": "Questo tipo di layer non può essere utilizzato come mappa di base.",
  "invalidBasemapUrl2": "La mappa di base che si sta aggiungendo ha un riferimento spaziale diverso dalla mappa corrente.",
  "addBaselayer": "Aggiungi layer mappa base",
  "repectOnline": "Sincronizzare sempre con l'impostazione Galleria di mappe di base dell'organizzazione",
  "customBasemap": "Configurare mappe di base personalizzate",
  "basemapTips": "Fare clic su \"${import}\" o \"${createNew}\" per aggiungere mappe di base.",
  "importBasemap": "Importa",
  "createBasemap": "Crea nuovo",
  "importTitle": "Importa mappe di base",
  "createTitle": "Nuova mappa di base",
  "selectGroupTip": "Selezionare un gruppo le cui mappe Web possono essere utilizzate come mappe di base.",
  "noBasemaps": "Nessuna mappa di base.",
  "defaultGroup": "Impostazioni predefinite Esri",
  "defaultOrgGroup": "Impostazione predefinita organizzazione",
  "warningTitle": "Avviso",
  "confirmDelete": "Eliminare le mappe di base selezionate?",
  "noBasemapAvailable": "Nessuna mappa di base disponibile, poiché tutte le mappe di base hanno un riferimento spaziale diverso dalla mappa corrente."
});