define({
  "taskUrl": "URL de Tarefa",
  "serviceURLPlaceholder": "Por favor introduza o URL de tarefa de Geoprocessamento",
  "layerOrder": "Ordem de camadas",
  "defaultValue": "Valor predefinido",
  "inputFeatureBy": "Elemento de entrada por",
  "renderer": "Renderizador",
  "displayType": "Exibir tipo",
  "helpUrl": "URL de Ajuda",
  "useResultMapService": "Visualizar resultado com um serviço de mapa.",
  "drawOnMap": "Desenhando no mapa de forma interativa",
  "selectLayer": "Selecionando uma camada no mapa",
  "shareResults": "Adicionar resultado como camada operacional",
  "setTask": "Definir",
  "setTaskTitle": "Tarefa GP selecionada",
  "enablePopup": "Ativar janelas popup",
  "unSupportGeometryType": "Não pode definir o renderizador devido ao tipo de geometria ser desconhecido.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Carregar ficheiro",
  "selectFileToUpload": "Seleccionar ficheiro...",
  "rasterFormat": "Formato de dados raster",
  "noFileSelected": "Nenhum ficheiro seleccionado!",
  "uploadSuccess": "Sucesso de carregamento de ficheiro!",
  "showLayerContent": "Exibir conteúdo da camada",
  "urlPlaceholder": "URL definido para elemento",
  "useShapefile": "Use shapefile no sistema de ficheiro local",
  "allowToExport": "Permitir exportar resultados",
  "useDynamicSchema": "A saída pode ter esquema diferente, usar esquema dinâmico em vez de pré-definido."
});