define({
  "_widgetLabel": "Çiz",
  "selectDrawMode": "Çizim modunu seç",
  "clear": "Temizle",
  "point": "Nokta",
  "line": "Çizgi",
  "polyline": "Çoklu Çizgi",
  "freehandPolyline": "Serbest çizim çoklu çizgi",
  "triangle": "Üçgen",
  "extent": "Kaplama",
  "circle": "Daire",
  "ellipse": "Elips",
  "polygon": "Alan",
  "freehandPolygon": "Serbest çizim alan",
  "text": "Metin",
  "style": "Stil",
  "alpha": "Saydamlık",
  "width": "Genişlik",
  "size": "Boyut",
  "color": "Renk",
  "markerColor": "İşaretçi rengi",
  "outlineColor": "Ana hat rengi",
  "lineColor": "Çizgi rengi",
  "fillColor": "Dolgu rengi",
  "showMeasurements": "Ölçümleri göster",
  "areaUnits": "Alan birimi",
  "distanceUnits": "Mesafe birimleri",
  "kilometers": "Kilometre",
  "miles": "Mil",
  "meters": "Metre",
  "feet": "Fit",
  "yards": "Yarda",
  "nauticalmiles": "Deniz mili",
  "squareKilometers": "Kilometre kare",
  "squareMiles": "Mil kare",
  "acres": "İngiliz Dönümü",
  "hectares": "Hektar",
  "squareMeters": "Metre kare",
  "squareFeet": "Feet kare",
  "squareYards": "Yarda kare",
  "undo": "Geri Al",
  "redo": "Yinele",
  "results": "Sonuçlar",
  "points": "Noktalar",
  "lines": "Çizgiler",
  "areas": "Alanlar"
});