define({
  "_widgetLabel": "Géotraitement",
  "_featureAction_ReceiveFeatureSet": "Définir en tant qu'entrée de ",
  "requiredInfo": "est obligatoire.",
  "drawnOnMap": "Le résultat apparaît sur la carte.",
  "noToolConfig": "Aucune tâche de géotraitement préconfigurée n'est disponible.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Télécharger le fichier",
  "selectFileToUpload": "Sélectionner un fichier...",
  "rasterFormat": "Format de données raster",
  "noFileSelected": "Aucun fichier sélectionné !",
  "uploadSuccess": "Chargement du fichier réussi !",
  "showLayerContent": "Afficher le contenu de la couche",
  "invalidUrl": "URL du service d'entités non valide",
  "urlPlaceholder": "URL du jeu d'entités",
  "addShapefile": "Ajouter un Shapefile",
  "generateShapefileError": "Erreur dans la génération du shapefile, veuillez vérifier : ",
  "cleared": "Le résultat a été effacé.",
  "enlargeView": "Agrandir la vue",
  "exportOutput": "Exporter",
  "emptyResult": "Le résultat est vide.",
  "useSelectedFeatureset": "Utilisez les entités obtenues.",
  "closeSelectedFeatureset": "Effacez et utilisez l'option en entrée configurée."
});