define({
  "_widgetLabel": "Geoprocessing",
  "_featureAction_ReceiveFeatureSet": "Instellen als input van ",
  "requiredInfo": "is vereist.",
  "drawnOnMap": "Het resultaat wordt getekend op de kaart.",
  "noToolConfig": "Geen vooraf geconfigureerde geoprocessing-taak beschikbaar.",
  "useUrlForGPInput": ".URL",
  "useUploadForGPInput": "Bestand uploaden",
  "selectFileToUpload": "Bestand selecteren...",
  "rasterFormat": "Bestandsformaat rooster",
  "noFileSelected": "Geen bestand geselecteerd!",
  "uploadSuccess": "Bestand met succes geüpload!",
  "showLayerContent": "Content van de laag weergeven",
  "invalidUrl": "Ongeldige feature service-URL",
  "urlPlaceholder": "Feature set URL",
  "addShapefile": "Shapefile toevoegen",
  "generateShapefileError": "Shapefile-fout genereren, controleer dan: ",
  "cleared": "Het resultaat is gewist.",
  "enlargeView": "Weergave vergroten",
  "exportOutput": "Exporteren",
  "emptyResult": "Het resultaat is leeg.",
  "useSelectedFeatureset": "Gebruik het/de resulterende object(en).",
  "closeSelectedFeatureset": "Wis en gebruik de geconfigureerde inputoptie.",
  "currentMapExtent": "Huidige kaartextent"
});