define({
  "showArcgisBasemaps": "כלול מפות בסיס של הפורטל",
  "add": "לחץ להוספת מפת בסיס חדשה",
  "edit": "מאפיינים",
  "titlePH": "כותרת מפת בסיס",
  "thumbnailHint": "לחץ על התמונה לעדכון",
  "urlPH": "כתובת URL של שכבה",
  "addlayer": "הוסף מפת בסיס",
  "warning": "קלט לא תקין",
  "save": "חזור ושמור",
  "back": "חזור ובטל",
  "addUrl": "הוסף URL",
  "autoCheck": "בדיקה אוטומטית",
  "checking": "בודק...",
  "result": "נשמר בהצלחה",
  "spError": "היחוס המרחבי בכל מפות הבסיס המתווספות לגלריה חייב להיות זהה.",
  "invalidTitle1": "מפת בסיס בשם '",
  "invalidTitle2": "' כבר קיימת. בחר כותרת אחרת.",
  "invalidBasemapUrl1": "שכבה מסוג זה אינה יכולה לשמש כמפת בסיס.",
  "invalidBasemapUrl2": "היחוס המרחבי במפת הבסיס שאתה מוסיף שונה מזה הקיים במפה הנוכחית.",
  "addBaselayer": "הוסף שכבה של מפת בסיס",
  "repectOnline": "סנכרן תמיד עם הגדרות גלריית מפות הבסיס של הארגון",
  "customBasemap": "קבע תצורה למפת בסיס מותאמת אישית",
  "basemapTips": "לחץ על \"${import}\" או על \"${createNew}\" כדי להוסיף מפות בסיס.",
  "importBasemap": "ייבא",
  "createBasemap": "צור חדש",
  "importTitle": "יבא מפות בסיס",
  "createTitle": "מפת בסיס חדשה",
  "selectGroupTip": "בחר קבוצה שבה יכולות מפות הבסיס לשמש כמפות בסיס.",
  "noBasemaps": "אין מפות בסיס.",
  "defaultGroup": "Esri ברירת מחדל",
  "defaultOrgGroup": "ברירת מחדל של הארגון",
  "warningTitle": "אזהרה",
  "confirmDelete": "האם ברצונך למחוק את מפות הבסיס שנבחרו?",
  "noBasemapAvailable": "אין מפות בסיס זמינות מפני שכל מפות הבסיס כוללות ייחוס מרחבי או סכמת אריחים שונים מאלו הקיימים במפה הנוכחית."
});