define({
  "showArcgisBasemaps": "Uwzględnij mapy bazowe z portalu",
  "add": "Kliknij, aby dodać nową mapę bazową",
  "edit": "Właściwości",
  "titlePH": "Tytuł mapy bazowej",
  "thumbnailHint": "Kliknij obraz do zaktualizowania",
  "urlPH": "Adres URL warstwy",
  "addlayer": "Dodaj mapę bazową",
  "warning": "Nieprawidłowe dane wejściowe",
  "save": "Wróć i zapisz",
  "back": "Wróć i anuluj",
  "addUrl": "Dodaj adres URL",
  "autoCheck": "Automatyczne sprawdzanie",
  "checking": "Trwa sprawdzanie...",
  "result": "Zapisano pomyślnie",
  "spError": "Wszystkie mapy bazowe dodane do galerii muszą mieć to samo odniesienie przestrzenne.",
  "invalidTitle1": "Mapa bazowa '",
  "invalidTitle2": "' już istnieje. Wybierz inny tytuł.",
  "invalidBasemapUrl1": "Warstwy tego typu nie można użyć jako mapy bazowej.",
  "invalidBasemapUrl2": "Dodawana mapa bazowa ma inne odniesienie przestrzenne od bieżącej mapy.",
  "addBaselayer": "Dodaj warstwę mapy bazowej",
  "repectOnline": "Zawsze synchronizuj z ustawieniem Galeria map bazowych instytucji",
  "customBasemap": "Konfiguruj niestandardowe mapy bazowe",
  "basemapTips": "Kliknij przycisk \"${import}\" lub \"${createNew}\", aby dodać mapy bazowe.",
  "importBasemap": "Importuj",
  "createBasemap": "Utwórz nowe",
  "importTitle": "Importuj mapy bazowe",
  "createTitle": "Nowa mapa bazowa",
  "selectGroupTip": "Wybierz grupę, której mapy internetowe mogą być używane jako mapy bazowe.",
  "noBasemaps": "Brak map bazowych.",
  "defaultGroup": "Wartość domyślna Esri",
  "defaultOrgGroup": "Wartość domyślna instytucji",
  "warningTitle": "Ostrzeżenie",
  "confirmDelete": "Czy chcesz usunąć wybrane mapy bazowe?",
  "noBasemapAvailable": "Brak dostępnych map bazowych, ponieważ wszystkie mapy bazowe mają inne odniesienie przestrzenne lub inny schemat kafli niż bieżąca mapa."
});