define({
  "_widgetLabel": "Nacrtaj",
  "selectDrawMode": "Izaberi režim crtanja",
  "clear": "Izbriši",
  "point": "Tačka",
  "line": "Linija",
  "polyline": "Polilinija",
  "freehandPolyline": "Polilinija slobodnom rukom",
  "triangle": "Trougao",
  "extent": "Pravougaonik",
  "circle": "Krug",
  "ellipse": "Elipsa",
  "polygon": "Poligon",
  "freehandPolygon": "Poligon crtan slobodnom rukom",
  "text": "Tekst",
  "style": "Stil",
  "alpha": "Prozirnost",
  "width": "Širina",
  "size": "Veličina",
  "color": "Boja",
  "markerColor": "Boja označivača",
  "outlineColor": "Boja kontura",
  "lineColor": "Boja linije",
  "fillColor": "Boja ispune",
  "showMeasurements": "Prikaži mere",
  "areaUnits": "Jedinice površine",
  "distanceUnits": "Jedinice rastojanja",
  "kilometers": "Kilometri",
  "miles": "Milje",
  "meters": "Metri",
  "feet": "Stope",
  "yards": "Jardi",
  "nauticalmiles": "Nautičke milje",
  "squareKilometers": "Kvadratni kilometri",
  "squareMiles": "Kvadratne milje",
  "acres": "Ari",
  "hectares": "Hektari",
  "squareMeters": "Kvadratni metri",
  "squareFeet": "Kvadratne stope",
  "squareYards": "Kvadratne jarde",
  "undo": "Opozovi radnju",
  "redo": "Ponovi radnju",
  "results": "Rezultati",
  "points": "Tačke",
  "lines": "Linije",
  "areas": "Površine"
});