define({
  "showArcgisBasemaps": "Sisällytä portaalin taustakartat",
  "add": "Lisää uusi taustakartta napsauttamalla",
  "edit": "Ominaisuudet",
  "titlePH": "Taustakartan otsikko",
  "thumbnailHint": "Päivitä napsauttamalla kuvaa",
  "urlPH": "Karttatason URL-osoite",
  "addlayer": "Lisää taustakartta",
  "warning": "Virheellinen lähtöaineisto",
  "save": "Takaisin ja tallenna",
  "back": "Takaisin ja peruuta",
  "addUrl": "Lisää URL-osoite",
  "autoCheck": "Automaattinen tarkistus",
  "checking": "Tarkistetaan...",
  "result": "Tallennus onnistui",
  "spError": "Kaikilla galleriaan lisätyillä taustakartoilla täytyy olla sama koordinaattijärjestelmä.",
  "invalidTitle1": "Taustakartta '",
  "invalidTitle2": "' on jo olemassa. Valitse toinen otsikko.",
  "invalidBasemapUrl1": "Tämän tyyppistä karttatasoa ei voi käyttää taustakarttana.",
  "invalidBasemapUrl2": "Lisättävän taustakartan koordinaattijärjestelmä ei ole sama kuin nykyisessä kartassa.",
  "addBaselayer": "Lisää taustakarttataso",
  "repectOnline": "Organisaation Synkronoi aina taustakarttagallerian kanssa -asetus",
  "customBasemap": "Määritä mukautetut taustakartat",
  "basemapTips": "Lisää taustakarttoja valitsemalla ${import} tai ${createNew}.",
  "importBasemap": "Tuo",
  "createBasemap": "Luo uusi",
  "importTitle": "Tuo taustakarttoja",
  "createTitle": "Uusi taustakartta",
  "selectGroupTip": "Valitse ryhmä, jonka taustakarttoja voi käyttää taustakarttoina.",
  "noBasemaps": "Ei taustakarttoja.",
  "defaultGroup": "Esri-oletusarvo",
  "defaultOrgGroup": "Organisaation oletus",
  "warningTitle": "Varoitus",
  "confirmDelete": "Haluatko poistaa valitut taustakartat?",
  "noBasemapAvailable": "Käytettävissä ei ole taustakarttoja, koska kaikilla taustakartoilla on eri sijaintiviite tai tiilirakenne kuin nykyisellä kartalla."
});