define({
  "taskUrl": "URL da Tarefa",
  "serviceURLPlaceholder": "Insira a URL da tarefa de geoprocessamento",
  "layerOrder": "Ordem da Camada",
  "defaultValue": "Valor padrão",
  "inputFeatureBy": "Feição de entrada por",
  "renderer": "Renderizador",
  "displayType": "Tipo de Exibição",
  "helpUrl": "URL de Ajuda",
  "useResultMapService": "Visualizar o resultado com um serviço de mapa",
  "drawOnMap": "Desenhar interativamente no mapa",
  "selectLayer": "Selecionando uma camada do mapa",
  "shareResults": "Adicionar resultado como camada operacional",
  "setTask": "Configurar",
  "setTaskTitle": "Definir Tarefa de GP",
  "enablePopup": "Habilitar pop-up",
  "unSupportGeometryType": "Não é possível configurar o renderizador devido ao tipo de geometria desconhecido.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Carregar arquivo",
  "selectFileToUpload": "Selecionar arquivo...",
  "rasterFormat": "Formato de dados raster",
  "noFileSelected": "Nenhum arquivo selecionado!",
  "uploadSuccess": "Arquivo carregado com sucesso!",
  "showLayerContent": "Mostrar conteúdo da camada",
  "urlPlaceholder": "URL de conjunto da feição",
  "useShapefile": "Utilizar shapefile no sistema de arquivos local",
  "allowToExport": "Permitir exportar os resultados",
  "useDynamicSchema": "A saída pode ter um esquema diferente, utilize esquema dinâmico, ao invés de pré-definido."
});