define({
  "_widgetLabel": "Γεωεπεξεργασία",
  "_featureAction_ReceiveFeatureSet": "Ορισμός ως είσοδος του ",
  "requiredInfo": "είναι προαπαιτούμενο.",
  "drawnOnMap": "Το αποτέλεσμα σχεδιάζεται στον χάρτη.",
  "noToolConfig": "Δεν έχει καθοριστεί εργασία γεωεπεξεργασίας.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Φόρτωση αρχείου",
  "selectFileToUpload": "Επιλογή αρχείου...",
  "rasterFormat": "Μορφότυπος πλεγματικών δεδομένων",
  "noFileSelected": "Δεν επιλέχθηκε αρχείο!",
  "uploadSuccess": "Επιτυχής φόρτωση αρχείου!",
  "showLayerContent": "Εμφάνιση περιεχομένου θεματικού επιπέδου",
  "invalidUrl": "Μη έγκυρο URL Feature Service",
  "urlPlaceholder": "URL συνόλου στοιχείων",
  "addShapefile": "Προσθήκη shapefile",
  "generateShapefileError": "Σφάλμα δημιουργίας του shapefile, ελέγξτε: ",
  "cleared": "Έγινε απαλοιφή του αποτελέσματος.",
  "enlargeView": "Μεγέθυνση προβολής",
  "exportOutput": "Εξαγωγή",
  "emptyResult": "Το αποτέλεσμα είναι κενό.",
  "useSelectedFeatureset": "Χρήση των στοιχείων που προέκυψαν.",
  "closeSelectedFeatureset": "Απαλοιφή και χρήση της επιλογής διαμόρφωσης εισόδου."
});