define({
  "_widgetLabel": "Vẽ",
  "selectDrawMode": "Chọn chế độ vẽ",
  "clear": "Xóa",
  "point": "Điểm",
  "line": "Đường",
  "polyline": "Đa tuyến",
  "freehandPolyline": "Đa tuyến vẽ tay",
  "triangle": "Hình tam giác",
  "extent": "Đường bao",
  "circle": "Hình tròn",
  "ellipse": "Hình Elip",
  "polygon": "Vùng",
  "freehandPolygon": "Vùng vẽ tự do",
  "text": "Văn bản",
  "style": "Kiểu",
  "alpha": "Độ trong suốt",
  "width": "Chiều rộng",
  "size": "Kích cỡ",
  "color": "Màu sắc",
  "markerColor": "Màu điểm đánh dấu",
  "outlineColor": "Màu đường viền",
  "lineColor": "Màu đường",
  "fillColor": "Tô màu",
  "showMeasurements": "Hiển thị các phép đo",
  "areaUnits": "Đơn vị diện tích",
  "distanceUnits": "Đơn vị khoảng cách",
  "kilometers": "Kilômét",
  "miles": "Dặm",
  "meters": "Mét",
  "feet": "Feet",
  "yards": "Thước",
  "nauticalmiles": "Hải lý",
  "squareKilometers": "Kilômét vuông",
  "squareMiles": "Dặm vuông",
  "acres": "Mẫu Anh",
  "hectares": "Hecta",
  "squareMeters": "Mét vuông",
  "squareFeet": "Feet vuông",
  "squareYards": "Thước vuông",
  "undo": "Hoàn tác",
  "redo": "Làm lại",
  "results": "Kết quả",
  "points": "Điểm",
  "lines": "Đường",
  "areas": "Khu vực"
});