define({
  "addDistance": "Dodaj enoto dolžine",
  "addArea": "Dodaj enoto območja",
  "label": "Napis",
  "abbr": "Okrajšava",
  "conversion": "Pretvorba",
  "actions": "Dejanja",
  "areaUnits": "Enote območja",
  "distanceUnits": "Enote dolžine",
  "kilometers": "Kilometri",
  "miles": "Milje",
  "meters": "Metri",
  "feet": "Čevlji",
  "yards": "Jardi",
  "nauticalmiles": "Morske milje",
  "squareKilometers": "Kvadratni kilometri",
  "squareMiles": "Kvadratne milje",
  "acres": "Akri",
  "hectares": "Hektarji",
  "squareMeters": "Kvadratni metri",
  "squareFeet": "Kvadratni čevlji",
  "squareYards": "Kvadratni jardi",
  "distance": "Razdalje",
  "area": "Območja",
  "kilometersAbbreviation": "km",
  "milesAbbreviation": "mi",
  "metersAbbreviation": "m",
  "feetAbbreviation": "ft",
  "yardsAbbreviation": "yd",
  "nauticalmilesAbbreviation": "nm",
  "squareKilometersAbbreviation": "km2",
  "squareMilesAbbreviation": "mi2",
  "acresAbbreviation": "ac",
  "hectaresAbbreviation": "ha",
  "squareMetersAbbreviation": "m2",
  "squareFeetAbbreviation": "ft2",
  "squareYardsAbbreviation": "yd2",
  "defineUnits": "Določi merske enote.",
  "operationalLayer": "Dodaj risbo kot operativni sloj karte."
});