define({
  "_widgetLabel": "Tulosta",
  "title": "Kartan otsikko",
  "format": "Tiedostomuoto",
  "layout": "Asettelu",
  "settings": "Lisäasetukset",
  "labels": "Tunnustekstit",
  "showLabels": "Näytä tunnustekstit",
  "mapScaleExtent": "Kartan mittakaava/laajuus",
  "preserve": "Säilytä",
  "mapScale": "Kartan mittakaava",
  "mapExtent": "Kartan laajuus",
  "forceScale": "Käytä mittakaavaa",
  "getCurrentScale": "nykyinen",
  "mapMetadata": "Taiton metadata",
  "author": "Tekijä",
  "copyright": "Copyright",
  "fullLayoutOptions": "Täydelliset asetteluvaihtoehdot",
  "scaleBarUnitsMetric": "Mittakaavapalkin yksiköt, metriset",
  "scaleBarUnitsNonMetric": "Mittakaavapalkin yksiköt, ei-metriset",
  "unitsMiles": "Mailia",
  "unitsKilometers": "Kilometriä",
  "unitsMeters": "Metriä",
  "unitsFeet": "Jalkaa",
  "unitsYards": "Jaardia",
  "unitsNauticalMiles": "Meripeninkulmaa",
  "lncludeLegend": "Sisällytä selite",
  "printQualityOptions": "Tulostuslaatu",
  "dpi": "DPI",
  "mapOnlyOptions": "KARTTA_VAIN koko",
  "width": "Leveys (px)",
  "height": "Korkeus (px)",
  "print": "Tulosta",
  "clearList": "Tyhjennä tulosteet",
  "creatingPrint": "Luodaan tulostetta",
  "printError": "Virhe, yritä uudelleen"
});