define({
  "showArcgisBasemaps": "Uključi pozadinske mape portala",
  "add": "Kliknite da biste dodali novu pozadinsku mapu",
  "edit": "Svojstva",
  "titlePH": "Naslov pozadinske mape",
  "thumbnailHint": "Kliknite na snimak da biste ažurirali",
  "urlPH": "URL adresa sloja",
  "addlayer": "Dodaj pozadinsku mapu",
  "warning": "Netačan unos",
  "save": "Nazad i sačuvaj",
  "back": "Nazad i otkaži",
  "addUrl": "Dodaj URL adresu",
  "autoCheck": "Automatsko proveravanje",
  "checking": "Proveravanje...",
  "result": "Uspešno sačuvano",
  "spError": "Sve pozadinske mape dodate u galeriju moraju da imaju istu prostornu referencu.",
  "invalidTitle1": "Pozadinska mapa „",
  "invalidTitle2": "“ već postoji. Izaberite drugi naslov.",
  "invalidBasemapUrl1": "Ovaj tip sloja ne može da bude korišćen kao pozadinska mapa.",
  "invalidBasemapUrl2": "Pozadinska mapa koju dodajete ima drugu prostornu referencu od trenutne mape.",
  "addBaselayer": "Dodaj sloj pozadinske mape",
  "repectOnline": "Uvek sinhronizuj sa postavkom Galerija pozadinskih mapa za organizaciju",
  "customBasemap": "Konfiguriši prilagođene pozadinske mape",
  "basemapTips": "Kliknite na \"${import}\" ili \"${createNew}\" da bist dodali pozadinske mape.",
  "importBasemap": "Uvezi",
  "createBasemap": "Kreiraj novo",
  "importTitle": "Uvezi pozadinske mape",
  "createTitle": "Nova pozadinska mapa",
  "selectGroupTip": "Izaberite grupu čije veb mape mogu da se koriste kao pozadinske mape.",
  "noBasemaps": "Nema pozadinskih mapa.",
  "defaultGroup": "Esri podrazumevano",
  "defaultOrgGroup": "Podrazumevano za organizaciju",
  "warningTitle": "Upozorenje",
  "confirmDelete": "Želite li da izbrišete izabrane pozadinske mape?",
  "noBasemapAvailable": "Nema dostupnih pozadinskih mapa, jer sve pozadinske mape imaju drugačiju prostornu referencu ili tajling šemu od aktuelne mape."
});