define({
  "_widgetLabel": "Geoprocessamento",
  "_featureAction_ReceiveFeatureSet": "Definir como entrada de ",
  "requiredInfo": "é necessário.",
  "drawnOnMap": "O resultado encontra-se desenhado no mapa.",
  "noToolConfig": "Não está disponível qualquer tarefa de geoprocessamento disponível.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Carregar ficheiro",
  "selectFileToUpload": "Seleccionar ficheiro...",
  "rasterFormat": "Formato de dados raster",
  "noFileSelected": "Nenhum ficheiro seleccionado!",
  "uploadSuccess": "Ficheiro actualizado com sucesso!",
  "showLayerContent": "Exibir conteúdo da camada",
  "invalidUrl": "Url de serviço de elementos inválido",
  "urlPlaceholder": "URL de conjunto de elementos",
  "addShapefile": "Adicionar Shapefile",
  "generateShapefileError": "Erro ao gerar shapefile, por favor verifique: ",
  "cleared": "O resultado foi apagado.",
  "enlargeView": "Ampliar visualização",
  "exportOutput": "Exportar",
  "emptyResult": "O resultado está vazio.",
  "useSelectedFeatureset": "Utilizar o(s) elemento(s) resultante(s).",
  "closeSelectedFeatureset": "Limpar e utilizar a opção de entrada configurada."
});