define({
  "_widgetLabel": "Geoprosessointi",
  "_featureAction_ReceiveFeatureSet": "Aseta seuraavan lähtöaineistoksi ",
  "requiredInfo": "vaaditaan.",
  "drawnOnMap": "Tulos piirretään kartalle.",
  "noToolConfig": "Yhtään ennalta määritettyä geoprosessointitehtävää ei ole käytettävissä.",
  "useUrlForGPInput": "URL-osoite",
  "useUploadForGPInput": "Lähetä tiedosto",
  "selectFileToUpload": "Valitse tiedosto...",
  "rasterFormat": "Rasteriaineiston muoto",
  "noFileSelected": "Yhtään tiedostoa ei ole valittu.",
  "uploadSuccess": "Tiedoston lataus onnistui.",
  "showLayerContent": "Näytä karttatason sisältö",
  "invalidUrl": "Virheellinen kohdepalvelun URL-osoite",
  "urlPlaceholder": "kohderyhmän URL-osoite",
  "addShapefile": "Lisää Shapefile",
  "generateShapefileError": "Luo shapefile-virhe, tarkista: ",
  "cleared": "Tulos on poistettu.",
  "enlargeView": "Laajenna näkymää",
  "exportOutput": "Vie",
  "emptyResult": "Tulos on tyhjä.",
  "useSelectedFeatureset": "Käytä saatua kohdetta / saatuja kohteita.",
  "closeSelectedFeatureset": "Tyhjennä ja käytä määritettyä lähtöaineistoasetusta.",
  "currentMapExtent": "Nykyinen kartan laajuus"
});