define({
  "_widgetLabel": "Geoprocessing",
  "_featureAction_ReceiveFeatureSet": "इसके इनपुट के रूप में निर्धारित करें ",
  "requiredInfo": "आवश्यक है।",
  "drawnOnMap": "परिणाम को मानचित्र पर बनाएं।",
  "noToolConfig": "पहले से कॉन्फ़िगर कोई भी geoprocessing कार्य उपलब्ध नहीं है।",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "फ़ाइल अपलोड करें",
  "selectFileToUpload": "फ़ाइल का चयन करें...",
  "rasterFormat": "रास्टर डेटा फॉर्मेट",
  "noFileSelected": "किसी भी फाइल का चयन नहीं किया गया है!",
  "uploadSuccess": "फ़ाइल सफलतापूर्वक अपलोड हो गई है!",
  "showLayerContent": "लेयर सामग्री दिखाएं",
  "invalidUrl": "अमान्य फीचर सेवा URL",
  "urlPlaceholder": "फीचर सेट URL",
  "addShapefile": "शेपफ़ाइल जोड़े",
  "generateShapefileError": "शेपफ़ाइल त्रुटि उत्पन्न हुई है, कृपया जाँच करें: ",
  "cleared": "परिणाम साफ़ कर दिए गए हैं।",
  "enlargeView": "दृश्य को बड़ा करें",
  "exportOutput": "निर्यात करें",
  "emptyResult": "परिणाम खाली है।",
  "useSelectedFeatureset": "परिणामी फीचर का प्रयोग करें।",
  "closeSelectedFeatureset": "कॉन्फ़िगर इनपुट ओपियन को साफ और उपयोग करें।"
});