define({
  "taskUrl": "Oppgave-URL",
  "serviceURLPlaceholder": "Angi oppgave-URLen for geoprosessering",
  "layerOrder": "Lagrekkefølge",
  "defaultValue": "Standardverdi",
  "inputFeatureBy": "Angi geoobjekter etter",
  "renderer": "Opptegning",
  "displayType": "Vis type",
  "helpUrl": "Hjelp-URL",
  "useResultMapService": "Vis resultatet med en karttjeneste",
  "drawOnMap": "Interaktiv tegning på kartet",
  "selectLayer": "Velge et kartlag fra kartet",
  "shareResults": "Legg til resultat som operativt kartlag",
  "setTask": "Angi",
  "setTaskTitle": "Angi GP-oppgave",
  "enablePopup": "Aktiver sprettoppvindu",
  "unSupportGeometryType": "Kan ikke angi opptegning på grunn av ukjent geometritype.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Last opp fil",
  "selectFileToUpload": "Velg fil...",
  "rasterFormat": "Rasterdataformat",
  "noFileSelected": "Ingen fil er valgt!",
  "uploadSuccess": "Filen er lastet opp.",
  "showLayerContent": "Vis laginnhold",
  "urlPlaceholder": "geoobjektsett-URL",
  "useShapefile": "Bruk shapefil i lokalt filsystem",
  "allowToExport": "Tillat eksport av resultater",
  "useDynamicSchema": "Utdataene kan ha annet skjema. Bruk dynamisk skjema i stedet for forhåndsdefinert."
});