define({
  "showArcgisBasemaps": "ポータルのベースマップを含める",
  "add": "クリックすると新規ベースマップが追加されます",
  "edit": "プロパティ",
  "titlePH": "ベースマップ タイトル",
  "thumbnailHint": "画像を変更するにはサムネイルをクリックします",
  "urlPH": "レイヤー URL",
  "addlayer": "ベースマップの追加",
  "warning": "不正な入力",
  "save": "保存して戻る",
  "back": "キャンセルして戻る",
  "addUrl": "URL の追加",
  "autoCheck": "自動チェック",
  "checking": "チェック中...",
  "result": "正常に保存されました",
  "spError": "ギャラリーに追加されるすべてのベースマップの空間参照は同じである必要があります。",
  "invalidTitle1": "ベースマップ '",
  "invalidTitle2": "' すでに存在しています。別のタイトルを選択してください。",
  "invalidBasemapUrl1": "このタイプのレイヤーは、ベースマップとして使用できません。",
  "invalidBasemapUrl2": "追加しているベースマップは、現在のマップとは空間参照が異なります。",
  "addBaselayer": "ベースマップ レイヤーの追加",
  "repectOnline": "組織のベースマップ ギャラリーの設定と常に同期",
  "customBasemap": "カスタム ベースマップの構成",
  "basemapTips": "\"${import}\" または \"${createNew}\" をクリックして、ベースマップを追加します。",
  "importBasemap": "インポート",
  "createBasemap": "新規作成",
  "importTitle": "ベースマップのインポート",
  "createTitle": "新規ベースマップ",
  "selectGroupTip": "Web マップをベースマップとして使用できるグループを選択します。",
  "noBasemaps": "ベースマップがありません。",
  "defaultGroup": "Esri デフォルト",
  "defaultOrgGroup": "組織のデフォルト",
  "warningTitle": "警告",
  "confirmDelete": "選択したベースマップを削除しますか？",
  "noBasemapAvailable": "すべてのベースマップの空間参照またはタイル スキーマが現在のマップと異なっているため、使用できるベースマップがありません。"
});