define({
  "_widgetLabel": "พิมพ์",
  "title": "ชื่อแผนที่",
  "format": "รูปแบบ",
  "layout": "แบบร่าง",
  "settings": "ระดับสูง",
  "labels": "ป้ายชื่อ",
  "showLabels": "แสดงตัวหนังสือ",
  "mapScaleExtent": "มาตราส่วนแผนที่/ขอบเขต",
  "preserve": "เก็บ",
  "mapScale": "มาตราส่วนแผนที่",
  "mapExtent": "ขอบเขตแผนที่",
  "forceScale": "มาตราส่วนบังคับ",
  "getCurrentScale": "ปัจจุบัน",
  "mapMetadata": "โครงร่าง Metadata",
  "author": "ผู้เขียน",
  "copyright": "ลิขสิทธิ์",
  "fullLayoutOptions": "ตัวเลือกโครงร่างแบบเต็ม",
  "scaleBarUnitsMetric": "แถบมาตราส่วนหน่วยเมตริก",
  "scaleBarUnitsNonMetric": "แถบมาตราส่วนหน่วยอื่นๆ",
  "unitsMiles": "ไมล์",
  "unitsKilometers": "กิโลเมตร",
  "unitsMeters": "เมตร",
  "unitsFeet": "ฟุต",
  "unitsYards": "หลา",
  "unitsNauticalMiles": "ไมล์ทะเล",
  "lncludeLegend": "รวมถึงคำอธิบาย",
  "printQualityOptions": "คุณภาพการพิมพ์",
  "dpi": "DPI",
  "mapOnlyOptions": "แผนที่_เท่านั้น ขนาด",
  "width": "ความกว้าง (px)",
  "height": "ความสูง (px)",
  "print": "พิมพ์",
  "clearList": "ล้างภาพพิมพ์",
  "creatingPrint": "การสร้างงานพิมพ์",
  "printError": "ข้อผิดพลาด ลองอีกครั้ง"
});