define({
  "taskUrl": "Åtgärds-URL",
  "serviceURLPlaceholder": "Ange URL för geobearbetningsåtgärden",
  "layerOrder": "Lagerordning",
  "defaultValue": "Standardvärde",
  "inputFeatureBy": "Indatageoobjekt efter",
  "renderer": "Renderare",
  "displayType": "Visningstyp",
  "helpUrl": "Hjälp-URL",
  "useResultMapService": "Visa resultat med en karttjänst",
  "drawOnMap": "Rita interaktivt på kartan",
  "selectLayer": "Välja ett lager från kartan",
  "shareResults": "Lägg till resultat som funktionslager",
  "setTask": "Ange",
  "setTaskTitle": "Ange geobearbetningsåtgärd",
  "enablePopup": "Aktivera popup-fönster",
  "unSupportGeometryType": "Det går inte att ställa in renderaren på grund av att geometritypen är okänd.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Överför fil",
  "selectFileToUpload": "Välj fil ...",
  "rasterFormat": "Rasterdataformat",
  "noFileSelected": "Ingen fil har valts!",
  "uploadSuccess": "Filen har överförts!",
  "showLayerContent": "Visa lagrets innehåll",
  "urlPlaceholder": "URL till geoobjektsuppsättning",
  "useShapefile": "Använd shapefilen i det lokala filsystemet",
  "allowToExport": "Tillåt export av resultat",
  "useDynamicSchema": "Resultatet kan ha ett annat schema. Använd ett dynamiskt schema i stället för ett fördefinierat."
});