define({
  "showArcgisBasemaps": "Inclui Mapas Base do Portal",
  "add": "Clique para adicionar um novo mapa base",
  "edit": "Propriedades",
  "titlePH": "Título do mapa base",
  "thumbnailHint": "Clique na imagem para atualizar",
  "urlPH": "URL da Camada",
  "addlayer": "Adicionar mapa base",
  "warning": "Entrada incorreta",
  "save": "Voltar e salvar",
  "back": "Voltar e cancelar",
  "addUrl": "Adicionar URL",
  "autoCheck": "Verificação automática",
  "checking": "Verificando...",
  "result": "Salvo com sucesso",
  "spError": "Todo os mapas base adicionados na galeria precisam ter a mesma referência espacial.",
  "invalidTitle1": "Um mapa base '",
  "invalidTitle2": "' já existe. Escolha outro título.",
  "invalidBasemapUrl1": "Este tipo de camada não pode ser utilizada como um mapa base.",
  "invalidBasemapUrl2": "O mapa base que você está adicionando tem uma referência espacial diferente do mapa atual.",
  "addBaselayer": "Adicionar camada de mapa base",
  "repectOnline": "Sempre sincronizar com a configuração da Galeria de Mapa Base da organização",
  "customBasemap": "Configurar mapas base personalizados",
  "basemapTips": "Clique em \"${import}\" ou \"${createNew}\" para adicionar maps base.",
  "importBasemap": "Importar",
  "createBasemap": "Criar novo",
  "importTitle": "Importar mapas base",
  "createTitle": "Novo mapa base",
  "selectGroupTip": "Seleciona um grupo cujo mapas da web podem ser utilizados como mapas base.",
  "noBasemaps": "Nenhum mapa base.",
  "defaultGroup": "Padrão Esri",
  "defaultOrgGroup": "Organização padrão",
  "warningTitle": "Aviso",
  "confirmDelete": "Deseja excluir os mapas base selecionados?",
  "noBasemapAvailable": "Não há mapas base disponíveis, pois todos os mapas base têm referência espacial ou esquema de mosaico diferente do mapa atual."
});