define({
  "addDistance": "Uzunluk birimi ekle",
  "addArea": "Alan birimi ekle",
  "label": "Etiket",
  "abbr": "Kısaltma",
  "conversion": "Dönüşüm",
  "actions": "İşlemler",
  "areaUnits": "Alan birimi",
  "distanceUnits": "Uzunluk birimi",
  "kilometers": "Kilometre",
  "miles": "Mil",
  "meters": "Metre",
  "feet": "Fit",
  "yards": "Yarda",
  "nauticalmiles": "Deniz mili",
  "squareKilometers": "Kilometre kare",
  "squareMiles": "Mil kare",
  "acres": "İngiliz Dönümü",
  "hectares": "Hektar",
  "squareMeters": "Metre kare",
  "squareFeet": "Feet kare",
  "squareYards": "Yarda kare",
  "distance": "Mesafeler",
  "area": "Alanlar",
  "kilometersAbbreviation": "km",
  "milesAbbreviation": "mi",
  "metersAbbreviation": "m",
  "feetAbbreviation": "ft",
  "yardsAbbreviation": "yrd",
  "nauticalmilesAbbreviation": "dm",
  "squareKilometersAbbreviation": "km²",
  "squareMilesAbbreviation": "mil²",
  "acresAbbreviation": "ar",
  "hectaresAbbreviation": "ha",
  "squareMetersAbbreviation": "m²",
  "squareFeetAbbreviation": "ft²",
  "squareYardsAbbreviation": "yd kare",
  "defineUnits": "Ölçüm birimlerini tanımlayın.",
  "operationalLayer": "Çizimi harita katmanının bir işlem katmanı olarak ekleyin."
});