define({
  "_widgetLabel": "Crtaj",
  "selectDrawMode": "Odabir načina crtanja",
  "clear": "Očisti",
  "point": "Točka",
  "line": "Linija",
  "polyline": "Polilinija",
  "freehandPolyline": "Prostoručna polilinija",
  "triangle": "Trokut",
  "extent": "Omotnica",
  "circle": "Krug",
  "ellipse": "Elipsa",
  "polygon": "Poligon",
  "freehandPolygon": "Prostoručni poligon",
  "text": "Tekst",
  "style": "Stil",
  "alpha": "Prozirnost",
  "width": "Širina",
  "size": "Veličina",
  "color": "Boja",
  "markerColor": "Boja oznake",
  "outlineColor": "Boja obrisa",
  "lineColor": "Boja linija",
  "fillColor": "Boja ispune",
  "showMeasurements": "Prikaži mjere",
  "areaUnits": "Površinske jedinice",
  "distanceUnits": "Jedinice udaljenosti",
  "kilometers": "Kilometri",
  "miles": "Milje",
  "meters": "Metri",
  "feet": "Stope",
  "yards": "Jardi",
  "nauticalmiles": "Nautičke milje",
  "squareKilometers": "Kvadratni kilometri",
  "squareMiles": "Kvadratne milje",
  "acres": "Jutra",
  "hectares": "Hektari",
  "squareMeters": "Kvadratni metri",
  "squareFeet": "Kvadratne stope",
  "squareYards": "Kvadratni jardi",
  "undo": "Poništi",
  "redo": "Ponovi",
  "results": "Rezultati",
  "points": "Točke",
  "lines": "Linije",
  "areas": "Područja"
});