define({
  "_widgetLabel": "Spausdinti",
  "title": "Žemėlapio pavadinimas",
  "format": "Formatuoti",
  "layout": "Maketas",
  "settings": "Išplėstinis",
  "labels": "Žymės",
  "showLabels": "Rodyti žymes",
  "mapScaleExtent": "Žemėlapio mastelis / aprėptis",
  "preserve": "Išlaikyti",
  "mapScale": "žemėlapio mastelis",
  "mapExtent": "žemėlapio aprėptis",
  "forceScale": "Priverstinis mastelis",
  "getCurrentScale": "dabartinis",
  "mapMetadata": "Maketo metaduomenys",
  "author": "Autorius",
  "copyright": "Autoriaus teisės",
  "fullLayoutOptions": "Visos maketo parinktys",
  "scaleBarUnitsMetric": "Mastelio juostos vienetai metriniai",
  "scaleBarUnitsNonMetric": "Mastelio juostos vienetai ne metriniai",
  "unitsMiles": "Mylios",
  "unitsKilometers": "Kilometrai",
  "unitsMeters": "Metrai",
  "unitsFeet": "Pėdos",
  "unitsYards": "Jardai",
  "unitsNauticalMiles": "Jūrmylės",
  "lncludeLegend": "Įtraukti legendą",
  "printQualityOptions": "Spausdinimo kokybė",
  "dpi": "DPI",
  "mapOnlyOptions": "MAP_ONLY dydis",
  "width": "Plotis (piks.)",
  "height": "Aukštis (piks.)",
  "print": "Spausdinti",
  "clearList": "Išvalyti spaudinius",
  "creatingPrint": "Kuriamas spaudinys",
  "printError": "Klaida, bandykite dar kartą"
});