define({
  "showArcgisBasemaps": "Vis bakgrunnskart fra portal",
  "add": "Klikk for å legge til nytt bakgrunnskart",
  "edit": "Egenskaper",
  "titlePH": "Tittel på bakgrunnskart",
  "thumbnailHint": "Klikk på bildet for å oppdatere",
  "urlPH": "Lag-URL",
  "addlayer": "Legg til bakgrunnskart",
  "warning": "Feil inndata",
  "save": "Tilbake og lagre",
  "back": "Tilbake og avbryt",
  "addUrl": "Legg til URL",
  "autoCheck": "Automatisk kontroll",
  "checking": "Kontrollerer ...",
  "result": "Lagring vellykket",
  "spError": "Alle bakgrunnskart som legges til i galleriet, må ha den samme geografiske referansesystem.",
  "invalidTitle1": "Bakgrunnskartet",
  "invalidTitle2": "finnes allerede. Du må velge en annen tittel.",
  "invalidBasemapUrl1": "Denne typen lag kan ikke brukes som bakgrunnskart.",
  "invalidBasemapUrl2": "Bakgrunnskartet du legger til har en annen geografisk referanse enn det gjeldende kartet.",
  "addBaselayer": "Legg til bakgrunnskartlag",
  "repectOnline": "Synkroniser alltid med organisasjonens innstilling for bakgrunnskartgalleri",
  "customBasemap": "Konfigurer egendefinerte bakgrunnskart",
  "basemapTips": "Klikk på \"${import}\" eller \"${createNew}\" for å legge til bakgrunnskart.",
  "importBasemap": "Importer",
  "createBasemap": "Opprett ny",
  "importTitle": "Importer bakgrunnskart",
  "createTitle": "Nytt bakgrunnskart",
  "selectGroupTip": "Velg en gruppe der gruppens webkart kan brukes som bakgrunnskart.",
  "noBasemaps": "Ingen bakgrunnskart.",
  "defaultGroup": "Esri standard",
  "defaultOrgGroup": "Organisasjonstandard",
  "warningTitle": "Advarsel",
  "confirmDelete": "Vil du slette bakgrunnskartene som er valgt?",
  "noBasemapAvailable": "Det er ingen tilgjengelige bakgrunnskart fordi alle bakgrunnskartene har annen romlig referanse eller fliseoppsett enn gjeldende kart."
});