define({
  "_widgetLabel": "Địa xử lý",
  "_featureAction_ReceiveFeatureSet": "Đặt làm đầu vào của ",
  "requiredInfo": "được yêu cầu.",
  "drawnOnMap": "Kết quả được vẽ trên bản đồ.",
  "noToolConfig": "Không có tác vụ địa xử lý nào được cấu hình sẵn.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Tải lên tệp",
  "selectFileToUpload": "Chọn tệp...",
  "rasterFormat": "Định dạng dữ liệu raster",
  "noFileSelected": "Không có tệp được chọn!",
  "uploadSuccess": "Tải lên tệp thành công!",
  "showLayerContent": "Hiển thị nội dung lớp",
  "invalidUrl": "Url của dịch vụ đối tượng không hợp lệ",
  "urlPlaceholder": "URL tập hợp đối tượng",
  "addShapefile": "Thêm Shapefile",
  "generateShapefileError": "Tạo lỗi shapefile, vui lòng kiểm tra: ",
  "cleared": "Kết quả đã được xóa bỏ.",
  "enlargeView": "Chế độ xem phóng to",
  "exportOutput": "Xuất",
  "emptyResult": "Kết quả trống.",
  "useSelectedFeatureset": "Sử dụng (các) đối tượng kết quả.",
  "closeSelectedFeatureset": "Xóa và sử dụng tùy chọn đầu vào được cấu hình."
});