define({
  "taskUrl": "Adres URL zadania",
  "serviceURLPlaceholder": "Wprowadź adres URL zadania geoprzetwarzania",
  "layerOrder": "Kolejność warstw",
  "defaultValue": "Wartość domyślna",
  "inputFeatureBy": "Wprowadź obiekt poprzez",
  "renderer": "Moduł renderowania",
  "displayType": "Typ wyświetlania",
  "helpUrl": "Adres URL Pomocy",
  "useResultMapService": "Wyświetl wynik przy użyciu usługi mapowej",
  "drawOnMap": "Interaktywne wyświetlanie na mapie",
  "selectLayer": "Wybór warstwy mapy",
  "shareResults": "Dodaj wynik jako warstwę operacyjną",
  "setTask": "Ustaw",
  "setTaskTitle": "Ustaw zadanie geoprzetwarzania",
  "enablePopup": "Włącz okno podręczne",
  "unSupportGeometryType": "Nie można skonfigurować modułu renderowania geometrii nieznanego typu.",
  "useUrlForGPInput": "Adres URL",
  "useUploadForGPInput": "Wczytaj plik",
  "selectFileToUpload": "Wybierz plik...",
  "rasterFormat": "Format danych wynikowych",
  "noFileSelected": "Nie wybrano pliku!",
  "uploadSuccess": "Pomyślnie przesłano plik!",
  "showLayerContent": "Wyświetl zawartość warstwy",
  "urlPlaceholder": "adres URL zestawów obiektów",
  "useShapefile": "Użyj pliku shape w lokalnym systemie plików",
  "allowToExport": "Udostępnij wyniki do eksportowania",
  "useDynamicSchema": "Dane wynikowe mogą mieć inny schemat, użyj schematu dynamicznego zamiast predefiniowanego.",
  "useCurrentMapExtent": "Użyj zasięgu bieżącej mapy",
  "ignoreOutput": "Ignoruj te dane wynikowe",
  "turnOffOutput": "Domyślnie wyłącz tę warstwę"
});