define({
  "taskUrl": "งาน URL",
  "serviceURLPlaceholder": "โปรดนำเข้างานด้านกระบวนการภูมิศาสตร์ URL",
  "layerOrder": "เรียงลำดับชั้นข้อมูล",
  "defaultValue": "ค่าเริ่มต้น",
  "inputFeatureBy": "ใส่ข้อมูลตั้งต้นโดย",
  "renderer": "แสดง",
  "displayType": "ประเภทการแสดง",
  "helpUrl": "ตัวช่วย URL",
  "useResultMapService": "ดูผลลัพธ์ด้วยบริการแผนที่",
  "drawOnMap": "การวาดแบบแผนที่แบบโต้ตอบอัตโนมัติ",
  "selectLayer": "การเลือกชั้นข้อมูลจากแผนที่",
  "shareResults": "เพิ่มผลลัพธ์เป็นชั้นข้อมูลเกี่ยวกับการดำเนินงาน",
  "setTask": "ตั้ง",
  "setTaskTitle": "ตั้งค่าการทำงาน GP",
  "enablePopup": "เปิดแสดงป็อปอัพ",
  "unSupportGeometryType": "ไม่สามารถกำหนดการเรนเดอร์ เนื่องจากไม่ทราบประเภทเรขาคณิต",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "อัพโหลดไฟล์",
  "selectFileToUpload": "เลือกไฟล์...",
  "rasterFormat": "รูปแบบข้อมูลราสเตอร์",
  "noFileSelected": "ไม่มีไฟล์ที่ถูกเลือก",
  "uploadSuccess": "อัพโหลดไฟล์สำเร็จ",
  "showLayerContent": "แสดงรายละเอียดชั้นข้อมูล",
  "urlPlaceholder": "การตั้งค่าคุณลักษณะ URL",
  "useShapefile": "ใช้ shapefile ในระบบไฟล์ท้องถิ่น",
  "allowToExport": "ยอมให้ส่งผลลัพธ์ออกไปได้",
  "useDynamicSchema": "ผลลัพท์อาจจะมีโครงสร้างต่างกันไป ใช้โครงสร้างที่ไดนามิก แทนการกำหนดไว้ล่วงหน้า",
  "useCurrentMapExtent": "ใช้ขอบเขตแผนที่ที่แสดงอยู่ในปัจจุบัน",
  "ignoreOutput": "เพิกเฉยต่อผลลัพธ์นี้",
  "turnOffOutput": "ปิดชั้นข้อมูลนี้ตามค่าเริ่มต้น"
});