define({
  "taskUrl": "कार्य का URL",
  "serviceURLPlaceholder": "कृपया Geoprocessing कार्य URL दर्ज करें",
  "layerOrder": "लेयर का क्रम",
  "defaultValue": "डिफ़ॉल्ट मान",
  "inputFeatureBy": "इसके द्वारा सुविधा इनपुट करें",
  "renderer": "रेंडरर",
  "displayType": "डिस्प्ले का प्रकार",
  "helpUrl": "सहायता के लिए URL",
  "useResultMapService": "मानचित्र सेवा के साथ परिणाम देखें",
  "drawOnMap": "मानचित्र पर परस्पर प्रभाव डालते हुए ड्राइंग करें",
  "selectLayer": "मानचित्र से एक लेयर का चयन करें",
  "shareResults": "परिचालन लेयर के रूप में परिणाम जोड़े",
  "setTask": "सेट करें",
  "setTaskTitle": "GP कार्य निर्धारित करें",
  "enablePopup": "पॉपअप सक्षम करें",
  "unSupportGeometryType": "अज्ञात ज्यामिति प्रकार की वजह से रेंडरर सेट नहीं किया जा सकता।",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "फ़ाइल अपलोड करें",
  "selectFileToUpload": "फ़ाइल का चयन करें...",
  "rasterFormat": "रास्टर डेटा फॉर्मेट",
  "noFileSelected": "किसी भी फाइल का चयन नहीं किया गया है!",
  "uploadSuccess": "फाइल को सफलतापूर्वक अपलोड कर लिया गया है!",
  "showLayerContent": "लेयर सामग्री दिखाएं",
  "urlPlaceholder": "फीचर सेट URL",
  "useShapefile": "स्थानीय फाइल सिस्टम में शेपफ़ाइल का प्रयोग करें",
  "allowToExport": "परिणाम को निर्यात करने की अनुमति देता है",
  "useDynamicSchema": "आउटपुट का अलग स्कीमा हो सकता हैं, पूर्वनिर्धारित के बजाय गतिशील स्कीमा उपयोग कर सकते हैं।",
  "useCurrentMapExtent": "वर्तमान मानचित्र सीमा का प्रयोग करें",
  "ignoreOutput": "इस आउटपुट को अनदेखा करें",
  "turnOffOutput": "डिफ़ॉल्ट रूप से इस लेयर को बंद करें"
});