define({
  "_widgetLabel": "Nariši",
  "selectDrawMode": "Izberite način risanja",
  "clear": "Počisti",
  "point": "Točka",
  "line": "Linija",
  "polyline": "Polilinija",
  "freehandPolyline": "Prostoročna polilinija",
  "triangle": "Trikotnik",
  "extent": "Ovojnica",
  "circle": "Krog",
  "ellipse": "Elipsa",
  "polygon": "Poligon",
  "freehandPolygon": "Prostoročni poligon",
  "text": "Besedilo",
  "style": "Slog",
  "alpha": "Prosojnost",
  "width": "Širina",
  "size": "Velikost",
  "color": "Barva",
  "markerColor": "Barva predstavitelja",
  "outlineColor": "Barva obrobe",
  "lineColor": "Barva linije",
  "fillColor": "Barva polnila",
  "showMeasurements": "Pokaži meritve",
  "areaUnits": "Enote območja",
  "distanceUnits": "Enote razdalje",
  "kilometers": "Kilometri",
  "miles": "Milje",
  "meters": "Metri",
  "feet": "Čevlji",
  "yards": "Jardi",
  "nauticalmiles": "Morske milje",
  "squareKilometers": "Kvadratni kilometri",
  "squareMiles": "Kvadratne milje",
  "acres": "Akri",
  "hectares": "Hektarji",
  "squareMeters": "Kvadratni metri",
  "squareFeet": "Kvadratni čevlji",
  "squareYards": "Kvadratni jardi",
  "undo": "Razveljavi",
  "redo": "Uveljavi",
  "results": "Rezultati",
  "points": "Točke",
  "lines": "Linije",
  "areas": "Območja"
});