define({
  "addDistance": "Dodaj jedinicu dužine",
  "addArea": "Dodaj jedinicu površine",
  "label": "Oznaka",
  "abbr": "Skraćenica",
  "conversion": "Konverzija",
  "actions": "Radnje",
  "areaUnits": "Jedinice površine",
  "distanceUnits": "Jedinice dužine",
  "kilometers": "Kilometri",
  "miles": "Milje",
  "meters": "Metri",
  "feet": "Stope",
  "yards": "Jardi",
  "nauticalmiles": "Nautičke milje",
  "squareKilometers": "Kvadratni kilometri",
  "squareMiles": "Kvadratne milje",
  "acres": "Ari",
  "hectares": "Hektari",
  "squareMeters": "Kvadratni metri",
  "squareFeet": "Kvadratne stope",
  "squareYards": "Kvadratne jarde",
  "distance": "Rastojanja",
  "area": "Površine",
  "kilometersAbbreviation": "km",
  "milesAbbreviation": "mi",
  "metersAbbreviation": "m",
  "feetAbbreviation": "ft",
  "yardsAbbreviation": "yd",
  "nauticalmilesAbbreviation": "nm",
  "squareKilometersAbbreviation": "km²",
  "squareMilesAbbreviation": "mi²",
  "acresAbbreviation": "a",
  "hectaresAbbreviation": "ha",
  "squareMetersAbbreviation": "m²",
  "squareFeetAbbreviation": "ft²",
  "squareYardsAbbreviation": "yd²",
  "defineUnits": "Definišite jedinice mere.",
  "operationalLayer": "Dodajte crtež kao operativni sloj mape."
});