define({
  "taskUrl": "Uzdevuma URL",
  "serviceURLPlaceholder": "Lūdzu, ievadiet ģeoapstrādes uzdevuma URL",
  "layerOrder": "Slāņu secība",
  "defaultValue": "Noklusējuma vērtība",
  "inputFeatureBy": "Ievadīt elementu pēc",
  "renderer": "Renderētājs",
  "displayType": "Parādīt veidu",
  "helpUrl": "Palīdzības URL",
  "useResultMapService": "Skatīt rezultātu, izmantojot karšu pakalpojumu",
  "drawOnMap": "Interaktīva zīmēšana kartē",
  "selectLayer": "Slāņa izvēle kartē",
  "shareResults": "Pievienot rezultātu kā operacionālo slāni",
  "setTask": "Iestatīt",
  "setTaskTitle": "Iestatīt GP uzdevumu",
  "enablePopup": "Iespējot uznirstošo logu",
  "unSupportGeometryType": "Nevar iestatīt renderētāju nezināma ģeometrijas tipa dēļ.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Augšupielādējiet failu",
  "selectFileToUpload": "Atlasiet failu...",
  "rasterFormat": "Rastra datu formāts",
  "noFileSelected": "Nav atlasīts fails!",
  "uploadSuccess": "Faila augšupielāde veiksmīga!",
  "showLayerContent": "Rādīt slāņa saturu",
  "urlPlaceholder": "elementu kopas URL",
  "useShapefile": "Izmantot Shape failu lokālajā failu sistēmā",
  "allowToExport": "Atļaut eksportēt rezultātus",
  "useDynamicSchema": "Izvadei varētu būt cita shēma; izmantojiet dinamisko shēmu, nevis iepriekš noteiktu shēmu.",
  "useCurrentMapExtent": "Lieto pašreizējo kartes pārklājumu",
  "ignoreOutput": "Ignorēt šo izvadi",
  "turnOffOutput": "Pēc noklusējuma izslēgt šo slāni"
});