define({
  "taskUrl": "タスク URL",
  "serviceURLPlaceholder": "ジオプロセシング タスク URL を入力してください",
  "layerOrder": "レイヤーの順序",
  "defaultValue": "デフォルト値",
  "inputFeatureBy": "フィーチャの入力方法:",
  "renderer": "レンダリング",
  "displayType": "表示タイプ",
  "helpUrl": "ヘルプ URL",
  "useResultMapService": "マップ サービスに結果を表示",
  "drawOnMap": "マップ上での対話的な描画",
  "selectLayer": "マップからレイヤーを選択",
  "shareResults": "操作レイヤーとして結果を追加",
  "setTask": "設定",
  "setTaskTitle": "ジオプロセシング タスクの設定",
  "enablePopup": "ポップアップの有効化",
  "unSupportGeometryType": "ジオメトリ タイプが不明なため、レンダラーを設定できません。",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "ファイルのアップロード",
  "selectFileToUpload": "ファイルの選択...",
  "rasterFormat": "ラスター データ形式",
  "noFileSelected": "ファイルが選択されませんでした。",
  "uploadSuccess": "ファイルが正常にアップロードされました。",
  "showLayerContent": "レイヤー コンテンツの表示",
  "urlPlaceholder": "フィーチャ セット URL",
  "useShapefile": "ローカル ファイル システムのシェープファイルの使用",
  "allowToExport": "結果のエクスポートを許可",
  "useDynamicSchema": "出力に、異なるスキーマが含まれている可能性があります。定義済みスキーマではなく、動的スキーマを使用してください。"
});