define({
  root: ({
    taskUrl: "Task URL",
    serviceURLPlaceholder: "Please input Geoprocessing task URL",
    layerOrder: "Layer order",
    defaultValue: "Default value",
    inputFeatureBy: "Input feature by",
    renderer: "Renderer",
    displayType: "Display type",
    helpUrl: "Help URL",
    useResultMapService: "View result with a map service",
    drawOnMap: "Interactively drawing on the map",
    selectLayer: "Selecting a layer from the map",
    shareResults: "Add result as operational layer",
    setTask: "Set",
    setTaskTitle: "Set GP task",
    enablePopup: "Enable popup",
    unSupportGeometryType: "Can not set renderer because of unknown geometry type.",
    useUrlForGPInput: "URL",
    useUploadForGPInput: "Upload file",
    selectFileToUpload: "Select file...",
    rasterFormat: "Raster data format",
    noFileSelected: "No file selected!",
    uploadSuccess: "Uploaded file successfully!",
    showLayerContent: "Show layer content",
    urlPlaceholder: "feature set URL",
    useShapefile: "Use shapefile in local file system",
    allowToExport: "Allow to export results",
    useDynamicSchema: "Output may have different schema, use dynamic schema instead of predefined."
  }),
  "ar": 1,
  "bs": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hi": 1,
  "hr": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
