define({
  "taskUrl": "任务 URL",
  "serviceURLPlaceholder": "请输入地理处理任务 URL",
  "layerOrder": "图层顺序",
  "defaultValue": "默认值",
  "inputFeatureBy": "输入要素",
  "renderer": "渲染器",
  "displayType": "显示类型",
  "helpUrl": "帮助 URL",
  "useResultMapService": "通过地图服务查看结果",
  "drawOnMap": "在地图上交互绘制",
  "selectLayer": "从地图选择图层",
  "shareResults": "将结果添加为业务图层",
  "setTask": "设置",
  "setTaskTitle": "设置 GP 任务",
  "enablePopup": "启用弹出窗口",
  "unSupportGeometryType": "由于几何类型未知，因此无法设置渲染器。",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "上传文件",
  "selectFileToUpload": "选择文件...",
  "rasterFormat": "栅格数据格式",
  "noFileSelected": "未选择任何文件!",
  "uploadSuccess": "文件上传成功!",
  "showLayerContent": "显示图层内容",
  "urlPlaceholder": "要素集 URL",
  "useShapefile": "在本地文件系统中使用 shapefile",
  "allowToExport": "允许导出结果",
  "useDynamicSchema": "输出可能具有不同方案，请使用动态方案代替预定义方案。"
});