define({
  "taskUrl": "任務 URL",
  "serviceURLPlaceholder": "請輸入地理處理任務 URL",
  "layerOrder": "圖層順序",
  "defaultValue": "預設值",
  "inputFeatureBy": "輸入圖徵",
  "renderer": "著色器",
  "displayType": "顯示類型",
  "helpUrl": "說明 URL",
  "useResultMapService": "使用地圖服務檢視結果",
  "drawOnMap": "在地圖上互動繪製",
  "selectLayer": "從地圖選擇圖層",
  "shareResults": "將結果新增為操作圖層",
  "setTask": "設定",
  "setTaskTitle": "設定 GP 任務",
  "enablePopup": "啟用彈出訊息",
  "unSupportGeometryType": "由於幾何類型未知，因此無法設定著色器。",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "上傳檔案",
  "selectFileToUpload": "選擇檔案...",
  "rasterFormat": "光柵資料格式",
  "noFileSelected": "未選擇任何檔案!",
  "uploadSuccess": "檔案上傳成功!",
  "showLayerContent": "顯示圖層內容",
  "urlPlaceholder": "圖徵設定 URL",
  "useShapefile": "使用本機檔案系統中的 shapefile",
  "allowToExport": "允許匯出結果",
  "useDynamicSchema": "輸出可能有不同的方案，請使用動態方案而非預定義的方案。"
});