define({
  "_widgetLabel": "Cetak",
  "title": "Judul peta",
  "format": "Format",
  "layout": "Layout",
  "settings": "Lanjutan",
  "labels": "Label",
  "showLabels": "Tampilkan label",
  "mapScaleExtent": "Skala/perluasan peta",
  "preserve": "Pemeliharaan",
  "mapScale": "skala peta",
  "mapExtent": "perluasan peta",
  "forceScale": "Paksakan skala",
  "getCurrentScale": "saat ini",
  "mapMetadata": "Metadata tata letak",
  "author": "Pembuat",
  "copyright": "Hak cipta",
  "fullLayoutOptions": "Opsi tata letak penuh",
  "scaleBarUnitsMetric": "Unit bilah skala metrik",
  "scaleBarUnitsNonMetric": "Unit bilah skala non-metrik",
  "unitsMiles": "Mil",
  "unitsKilometers": "Kilometer",
  "unitsMeters": "Meter",
  "unitsFeet": "Kaki",
  "unitsYards": "Yard",
  "unitsNauticalMiles": "Mil laut",
  "lncludeLegend": "Sertakan legenda",
  "printQualityOptions": "Kualitas cetak",
  "dpi": "DPI",
  "mapOnlyOptions": "Ukuran MAP_ONLY",
  "width": "Lebar (px)",
  "height": "Tinggi (px)",
  "print": "Cetak",
  "clearList": "Bersihkan cetakan",
  "creatingPrint": "Membuat cetakan",
  "printError": "Eror, coba lagi"
});