define({
  "_widgetLabel": "Geoprocesamiento",
  "_featureAction_ReceiveFeatureSet": "Definir como entrada de ",
  "requiredInfo": "es obligatorio.",
  "drawnOnMap": "El resultado se dibuja en el mapa.",
  "noToolConfig": "No hay ninguna tarea de geoprocesamiento preconfigurada disponible.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Cargar archivo",
  "selectFileToUpload": "Seleccionar archivo...",
  "rasterFormat": "Formato de datos ráster",
  "noFileSelected": "No hay ningún archivo seleccionado",
  "uploadSuccess": "Carga de archivos correcta",
  "showLayerContent": "Mostrar contenido de capa",
  "invalidUrl": "Dirección URL del servicio de entidades no válida",
  "urlPlaceholder": "Dirección URL del conjunto de entidades",
  "addShapefile": "Agregar shapefile",
  "generateShapefileError": "Error de generador de shapefile, comprueba: ",
  "cleared": "Se ha borrado el resultado.",
  "enlargeView": "Agrandar vista",
  "exportOutput": "Exportar",
  "emptyResult": "El resultado está vacío.",
  "useSelectedFeatureset": "Use las entidades resultantes.",
  "closeSelectedFeatureset": "Borre y use la opción de entrada configurada.",
  "currentMapExtent": "Extensión de mapa actual"
});