define({
  "_widgetLabel": "Geoprocessing",
  "_featureAction_ReceiveFeatureSet": "הגדר כקלט של ",
  "requiredInfo": "נדרש.",
  "drawnOnMap": "התוצאה מוצגת במפה.",
  "noToolConfig": "אין משימת עיבוד נתונים זמינה שהוגדרה מראש.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "טעינת קובץ",
  "selectFileToUpload": "בחר קובץ...",
  "rasterFormat": "פורמט נתוני רסטר",
  "noFileSelected": "לא נבחר קובץ!",
  "uploadSuccess": "הקובץ נטען בהצלחה!",
  "showLayerContent": "הצג תוכן שכבה",
  "invalidUrl": "כתובת ה-URL של שירות הישויות לא חוקית",
  "urlPlaceholder": "URL של סט ישויות",
  "addShapefile": "הוסף Shapefile",
  "generateShapefileError": "שגיאה ביצירת Shapefile, נא בדוק: ",
  "cleared": "התוצאה נוקתה.",
  "enlargeView": "הגדל תצוגה",
  "exportOutput": "ייצא",
  "emptyResult": "התוצאה ריקה.",
  "useSelectedFeatureset": "השתמש בישויות שעולות בתוצאות.",
  "closeSelectedFeatureset": "נקה והשתמש באפשרות הקלט המוגדרת."
});