define({
  "taskUrl": "URL של המשימה",
  "serviceURLPlaceholder": "אנא הכנס URL של משימת geoprocessing",
  "layerOrder": "סדר שכבה",
  "defaultValue": "ערך ברירת מחדל",
  "inputFeatureBy": "ישויות קלט לפי",
  "renderer": "Renderer",
  "displayType": "הצג סוג",
  "helpUrl": "URL עזרה",
  "useResultMapService": "הצג תוצאה עם שירות מפה",
  "drawOnMap": "ציור אינטראקטיבי במפה",
  "selectLayer": "בחירת שכבה מהמפה",
  "shareResults": "הוסף תוצאה כשכבה תפעולית",
  "setTask": "הגדר",
  "setTaskTitle": "הגדר משימת GP",
  "enablePopup": "אפשר חלון קופץ",
  "unSupportGeometryType": "לא ניתן להגדיר Renderer בשל סוג גיאומטריה לא מוכר.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "טעינת קובץ",
  "selectFileToUpload": "בחר קובץ...",
  "rasterFormat": "פורמט נתוני רסטר",
  "noFileSelected": "לא נבחר קובץ!",
  "uploadSuccess": "טעינת הקובץ בוצעה בהצלחה!",
  "showLayerContent": "הצג תוכן שכבה",
  "urlPlaceholder": "URL של סט ישויות",
  "useShapefile": "השתמש ב-Shapefile במערכת הקבצים המקומית",
  "allowToExport": "אפשר לייצא תוצאות",
  "useDynamicSchema": "ייתכן שהפלט יכלול סכימה שונה, השתמש בסכימה דינמית במקום בסכימה מוגדרת מראש.",
  "useCurrentMapExtent": "השתמש בתיחום המפה הנוכחי",
  "ignoreOutput": "התעלם מפלט זה",
  "turnOffOutput": "כבה שכבה זו כברירת מחדל"
});