define({
  "addDistance": "הוסף יחידת אורך",
  "addArea": "הוסף יחידת שטח",
  "label": "תווית",
  "abbr": "קיצור",
  "conversion": "המרה",
  "actions": "פעולות",
  "areaUnits": "יחידות שטח",
  "distanceUnits": "יחידות אורך",
  "kilometers": "קילומטרים",
  "miles": "מיילים",
  "meters": "מטרים",
  "feet": "רגל",
  "yards": "יארד",
  "nauticalmiles": "מיילים ימיים",
  "squareKilometers": "קילומטרים רבועים",
  "squareMiles": "מיילים רבועים",
  "acres": "אקרים",
  "hectares": "הקטרים",
  "squareMeters": "מטרים רבועים",
  "squareFeet": "רגל רבוע",
  "squareYards": "יארדים רבועים",
  "distance": "מרחקים",
  "area": "שטחים",
  "kilometersAbbreviation": "קילומטר",
  "milesAbbreviation": "מייל",
  "metersAbbreviation": "מטר",
  "feetAbbreviation": "רגל",
  "yardsAbbreviation": "יארד",
  "nauticalmilesAbbreviation": "מייל ימי",
  "squareKilometersAbbreviation": "קמ\"ר",
  "squareMilesAbbreviation": "מייל רבוע",
  "acresAbbreviation": "אקר",
  "hectaresAbbreviation": "הקטר",
  "squareMetersAbbreviation": "מ\"ר",
  "squareFeetAbbreviation": "‏‫רגל רבוע",
  "squareYardsAbbreviation": "יארד רבוע",
  "defineUnits": "הגדר את יחידות המדידה.",
  "operationalLayer": "הוסף את השרטוט כשכבה תפעולית במפה."
});