define({
  "addDistance": "लंबाई की इकाई जोड़ें",
  "addArea": "क्षेत्रफल की इकाई जोड़ें",
  "label": "लेबल",
  "abbr": "संक्षिप्त नाम",
  "conversion": "परिवर्तन",
  "actions": "कार्रवाइयाँ",
  "areaUnits": "क्षेत्र इकाइयाँ",
  "distanceUnits": "लंबाई की इकाइयाँ",
  "kilometers": "किलोमीटर",
  "miles": "मील",
  "meters": "मीटर",
  "feet": "फ़ीट",
  "yards": "गज",
  "nauticalmiles": "समुद्री मील",
  "squareKilometers": "वर्ग किलोमीटर",
  "squareMiles": "वर्ग मील",
  "acres": "एकड़",
  "hectares": "हेक्टेयर",
  "squareMeters": "वर्ग मीटर",
  "squareFeet": "वर्ग फीट",
  "squareYards": "वर्ग गज",
  "distance": "दूरी",
  "area": "क्षेत्रों",
  "kilometersAbbreviation": "km",
  "milesAbbreviation": "mi",
  "metersAbbreviation": "m",
  "feetAbbreviation": "ft",
  "yardsAbbreviation": "गज",
  "nauticalmilesAbbreviation": "nm",
  "squareKilometersAbbreviation": "वर्ग किमी",
  "squareMilesAbbreviation": "वर्ग मील",
  "acresAbbreviation": "एकड़",
  "hectaresAbbreviation": "हैक्टेयर",
  "squareMetersAbbreviation": "वर्ग मीटर",
  "squareFeetAbbreviation": "वर्ग फीट",
  "squareYardsAbbreviation": "वर्ग गज",
  "defineUnits": "माप की इकाईयां निर्धारित करें।",
  "operationalLayer": "ड्राइंग को मानचित्र की संचालन लेयर के रूप में जोड़ें।"
});