define({
  "_widgetLabel": "Zeichnen",
  "selectDrawMode": "Darstellungsmodus auswählen",
  "clear": "Löschen",
  "point": "Punkt",
  "line": "Linie",
  "polyline": "Polylinie",
  "freehandPolyline": "Freihand-Polylinie",
  "triangle": "Dreieck",
  "extent": "Envelope",
  "circle": "Kreis",
  "ellipse": "Ellipse",
  "polygon": "Polygon",
  "freehandPolygon": "Freihand-Polygon",
  "text": "Text",
  "style": "Style",
  "alpha": "Transparenz",
  "width": "Breite",
  "size": "Größe",
  "color": "Farbe",
  "markerColor": "Markerfarbe",
  "outlineColor": "Umrissfarbe",
  "lineColor": "Linienfarbe",
  "fillColor": "Füllfarbe",
  "showMeasurements": "Messwerte anzeigen",
  "areaUnits": "Flächeneinheiten",
  "distanceUnits": "Abstandseinheiten",
  "kilometers": "Kilometer",
  "miles": "Meilen",
  "meters": "Meter",
  "feet": "Fuß",
  "yards": "Yard",
  "nauticalmiles": "Seemeilen",
  "squareKilometers": "Quadratkilometer",
  "squareMiles": "Quadratmeilen",
  "acres": "Acres",
  "hectares": "Hektar",
  "squareMeters": "Quadratmeter",
  "squareFeet": "Quadratfuß",
  "squareYards": "Quadratyard",
  "undo": "Rückgängig",
  "redo": "Wiederholen",
  "results": "Ergebnisse",
  "points": "Punkte",
  "lines": "Linien",
  "areas": "Flächen"
});