define({
  "showArcgisBasemaps": "包括 Portal 的底圖",
  "add": "按一下以新增新底圖",
  "edit": "設定",
  "titlePH": "底圖標題",
  "thumbnailHint": "按一下圖片進行更新",
  "urlPH": "圖層 URL",
  "addlayer": "新增底圖",
  "warning": "輸入不正確",
  "save": "返回並儲存",
  "back": "返回並取消",
  "addUrl": "新增 URL",
  "autoCheck": "自動檢查",
  "checking": "正在檢查...",
  "result": "已成功儲存",
  "spError": "新增到圖庫的所有底圖必須具有相同的空間參考。",
  "invalidTitle1": "底圖 '",
  "invalidTitle2": "' 已存在。請選擇其它標題。",
  "invalidBasemapUrl1": "此類型的圖層不能做為底圖。",
  "invalidBasemapUrl2": "您正在新增的底圖與目前地圖擁有不同的空間參考。",
  "addBaselayer": "新增底圖圖層",
  "repectOnline": "一律與組織的基圖圖庫設定同步",
  "customBasemap": "配置自訂底圖",
  "basemapTips": "按一下 \"${import}\" 或 \"${createNew}\" 以增加底圖。",
  "importBasemap": "匯入",
  "createBasemap": "新建",
  "importTitle": "匯入底圖",
  "createTitle": "新增底圖",
  "selectGroupTip": "選擇可將其 Web 地圖作為底圖的群組。",
  "noBasemaps": "無底圖。",
  "defaultGroup": "Esri 預設值",
  "defaultOrgGroup": "組織預設值",
  "warningTitle": "警告",
  "confirmDelete": "是否要刪除選取的底圖?",
  "noBasemapAvailable": "沒有可用的底圖，因為所有底圖與目前地圖擁有不同的空間參考或圖磚方案。"
});