define({
  "taskUrl": "URL naloge",
  "serviceURLPlaceholder": "Vnesite URL geoprocesne naloge",
  "layerOrder": "Vrstni red slojev",
  "defaultValue": "Privzeta vrednost",
  "inputFeatureBy": "Vnesi geoobjekt po",
  "renderer": "Upodabljalnik",
  "displayType": "Prikaži tip",
  "helpUrl": "URL pomoči",
  "useResultMapService": "Pogled rezultata s kartno storitvijo",
  "drawOnMap": "Interaktivno risanje na karti",
  "selectLayer": "Izbiranje sloja s trenutne karte",
  "shareResults": "Dodaj rezultat kot operativni sloj",
  "setTask": "Nastavi",
  "setTaskTitle": "Nastavi nalogo GP",
  "enablePopup": "Omogoči pojavno okno",
  "unSupportGeometryType": "Upodabljalnika ni mogoče nastaviti zaradi neznanega tipa geometrije.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Naloži datoteko",
  "selectFileToUpload": "Izberi datoteko...",
  "rasterFormat": "Oblika podatkov rastra",
  "noFileSelected": "Nobena datoteka ni izbrana!",
  "uploadSuccess": "Datoteka je bila uspešno naložena!",
  "showLayerContent": "Pokaži vsebino sloja",
  "urlPlaceholder": "URL nabora geoobjektov",
  "useShapefile": "Uporabi shapefile v lokalnem sistemu datotek",
  "allowToExport": "Dovoli izvoz rezultatov",
  "useDynamicSchema": "Izhod ima lahko drugačno shemo, uporabite dinamično shemo namesto prednastavljene.",
  "useCurrentMapExtent": "Uporabi trenutni obseg karte",
  "ignoreOutput": "Prezri ta rezultat",
  "turnOffOutput": "Privzeto izklopi ta sloj"
});