define({
  "_widgetLabel": "Geotöötlus",
  "_featureAction_ReceiveFeatureSet": "Määra järgmise sisendina ",
  "requiredInfo": "on nõutav.",
  "drawnOnMap": "Tulemus joonistatakse kaardile.",
  "noToolConfig": "Eelkonfigureeritud geotöötluse toimingud ei ole saadaval.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Faili üleslaadimine",
  "selectFileToUpload": "Vali fail...",
  "rasterFormat": "Rasterandmete formaat",
  "noFileSelected": "Ühtegi faili pole valitud!",
  "uploadSuccess": "Faili üleslaadimine oli edukas!",
  "showLayerContent": "Kuva kihi sisu",
  "invalidUrl": "Kehtetu objektiteenuse URL",
  "urlPlaceholder": "objektikomplekti URL",
  "addShapefile": "Lisa Shape-fail",
  "generateShapefileError": "Genereerige Shape-faili viga, kontrollige: ",
  "cleared": "Tulemus on kustutatud.",
  "enlargeView": "Suurenda vaadet",
  "exportOutput": "Ekspordi",
  "emptyResult": "Tulemus on tühi.",
  "useSelectedFeatureset": "Kasutage tulemusena saadud objekti (objekte).",
  "closeSelectedFeatureset": "Kustutage ja kasutage konfigureeritud sisendivalikut."
});