define({
  "_widgetLabel": "Geoprosessering",
  "_featureAction_ReceiveFeatureSet": "Angi som inndata for ",
  "requiredInfo": "er påkrevd.",
  "drawnOnMap": "Resultatet tegnes på kartet.",
  "noToolConfig": "Ingen forhåndskonfigurert geoprosesseringsoppgave tilgjengelig.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Last opp fil",
  "selectFileToUpload": "Velg fil...",
  "rasterFormat": "Rasterdataformat",
  "noFileSelected": "Ingen fil er valgt!",
  "uploadSuccess": "Filen er lastet opp.",
  "showLayerContent": "Vis laginnhold",
  "invalidUrl": "Ugyldig geoobjektstjeneste-URL",
  "urlPlaceholder": "geoobjektsett-URL",
  "addShapefile": "Legg til shapefil",
  "generateShapefileError": "Generer shapefilfeil. Kontroller: ",
  "cleared": "Resultatet er fjernet.",
  "enlargeView": "Forstørr visningen",
  "exportOutput": "Eksporter",
  "emptyResult": "Resultatet er tomt.",
  "useSelectedFeatureset": "Bruk resulterende geoobjekt(er).",
  "closeSelectedFeatureset": "Fjern og bruk det konfigurerte inndataalternativet."
});