define({
  "taskUrl": "URL задачи",
  "serviceURLPlaceholder": "Введите URL задачи геообработки",
  "layerOrder": "Порядок слоев",
  "defaultValue": "Значение по умолчанию",
  "inputFeatureBy": "Входные объекты по",
  "renderer": "Метод отображения",
  "displayType": "Тип отображения",
  "helpUrl": "URL Справки",
  "useResultMapService": "Просмотреть результат с помощью картографического сервиса",
  "drawOnMap": "Интерактивное рисование на карте",
  "selectLayer": "Выбор слоя карты",
  "shareResults": "Добавить результат как операционный слой",
  "setTask": "Задать",
  "setTaskTitle": "Установить задачу геообработки",
  "enablePopup": "Включить всплывающее окно",
  "unSupportGeometryType": "Не удается задать метод отображения из-за неизвестного типа геометрии.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Загрузить файл",
  "selectFileToUpload": "Выбрать файл...",
  "rasterFormat": "Формат растровых данных",
  "noFileSelected": "Нет выбранных файлов!",
  "uploadSuccess": "Файл успешно загружен!",
  "showLayerContent": "Показать ресурсы слоя",
  "urlPlaceholder": "URL-адрес группы объектов",
  "useShapefile": "Использовать шейп-файл в локальной файловой системе",
  "allowToExport": "Разрешить экспортировать результаты",
  "useDynamicSchema": "У выходных данных может быть другая схема, используйте динамическую схему вместо предустановленной.",
  "useCurrentMapExtent": "Использовать текущий экстент карты",
  "ignoreOutput": "Игнорировать эти выходные данные",
  "turnOffOutput": "Выключить этот слой по умолчанию"
});