define({
  "taskUrl": "Task-URL",
  "serviceURLPlaceholder": "Geben Sie die URL des Geoverarbeitungs-Task ein",
  "layerOrder": "Layer-Reihenfolge",
  "defaultValue": "Standardwert",
  "inputFeatureBy": "Eingabe-Feature nach",
  "renderer": "Renderer",
  "displayType": "Anzeigetyp",
  "helpUrl": "Hilfe-URL",
  "useResultMapService": "Ergebnisanzeige mit einem Kartenservice",
  "drawOnMap": "Interaktives Zeichnen auf der Karte",
  "selectLayer": "Auswahl eines Layers auf der Karte",
  "shareResults": "Ergebnis als operationalen Layer hinzufügen",
  "setTask": "Festlegen",
  "setTaskTitle": "GV-Task festlegen",
  "enablePopup": "Pop-up aktivieren",
  "unSupportGeometryType": "Renderer kann aufgrund des unbekannten Geometrietyps nicht festgelegt werden.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Datei hochladen",
  "selectFileToUpload": "Datei auswählen...",
  "rasterFormat": "Raster-Datenformat",
  "noFileSelected": "Keine Datei ausgewählt!",
  "uploadSuccess": "Datei wurde erfolgreich hochgeladen!",
  "showLayerContent": "Layer-Inhalt anzeigen",
  "urlPlaceholder": "Feature-Set-URL",
  "useShapefile": "Shapefile in lokalem Dateisystem verwenden",
  "allowToExport": "Exportieren von Ergebnissen zulassen",
  "useDynamicSchema": "Die Ausgabe kann verschiedene Schemas aufweisen; das dynamische anstelle des vordefinierten Schemas verwenden.",
  "useCurrentMapExtent": "Aktuelle Kartenausdehnung verwenden",
  "ignoreOutput": "Diese Ausgabe ignorieren",
  "turnOffOutput": "Diesen Layer standardmäßig deaktivieren"
});