define({
  "taskUrl": "URL zadatka",
  "serviceURLPlaceholder": "Unesite URL zadatka geoprocesiranja",
  "layerOrder": "Redoslijed slojeva",
  "defaultValue": "Zadana vrijednost",
  "inputFeatureBy": "Uvezi geoobjekt prema",
  "renderer": "Renderer",
  "displayType": "Prikaži vrstu",
  "helpUrl": "URL za pomoć",
  "useResultMapService": "Prikaži rezultate pomoću usluge karte",
  "drawOnMap": "Interaktivno crtanje na karti",
  "selectLayer": "Odabir sloja s karte",
  "shareResults": "Dodaj rezultat kao operativni sloj",
  "setTask": "Postavi",
  "setTaskTitle": "Postavi GP zadatak",
  "enablePopup": "Omogući skočni prozor",
  "unSupportGeometryType": "Ne može se postaviti renderer zbog nepoznate vrste geometrije.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Učitaj datoteku",
  "selectFileToUpload": "Odabir datoteke...",
  "rasterFormat": "Format rasterskog podataka",
  "noFileSelected": "Datoteka nije odabrana!",
  "uploadSuccess": "Datoteka uspješno učitana!",
  "showLayerContent": "Prikaži sadržaj sloja",
  "urlPlaceholder": "URL seta geoobjekata",
  "useShapefile": "Upotrijebi shapefile u lokalnom sustavu datoteka",
  "allowToExport": "Omogući izvoz rezultata",
  "useDynamicSchema": "Izvoz može imati drugačiju shemu, upotrijebite dinamičnu shemu umjesto predefinirane.",
  "useCurrentMapExtent": "Upotrijebi trenutačni obuhvat karte",
  "ignoreOutput": "Ignoriraj ove izlazne vrijednosti",
  "turnOffOutput": "Isključite ovaj sloj prema zadanim postavkama"
});