define({
  "addDistance": "Tambahkan unit panjang",
  "addArea": "Tambahkan unit area",
  "label": "Label",
  "abbr": "Singkatan",
  "conversion": "Konversi",
  "actions": "Tindakan",
  "areaUnits": "Unit area",
  "distanceUnits": "Unit panjang",
  "kilometers": "Kilometer",
  "miles": "Mil",
  "meters": "Meter",
  "feet": "Kaki",
  "yards": "Yard",
  "nauticalmiles": "Mil laut",
  "squareKilometers": "Kilometer persegi",
  "squareMiles": "Mil persegi",
  "acres": "Acre",
  "hectares": "Hektare",
  "squareMeters": "Meter persegi",
  "squareFeet": "Kaki persegi",
  "squareYards": "Yard persegi",
  "distance": "Jarak",
  "area": "Area",
  "kilometersAbbreviation": "km",
  "milesAbbreviation": "mi",
  "metersAbbreviation": "m",
  "feetAbbreviation": "ft",
  "yardsAbbreviation": "yd",
  "nauticalmilesAbbreviation": "nm",
  "squareKilometersAbbreviation": "km persegi",
  "squareMilesAbbreviation": "mi persegi",
  "acresAbbreviation": "ac",
  "hectaresAbbreviation": "ha",
  "squareMetersAbbreviation": "m persegi",
  "squareFeetAbbreviation": "kaki persegi",
  "squareYardsAbbreviation": "yd persegi",
  "defineUnits": "Tetapkan unit pengukuran.",
  "operationalLayer": "Tambahkan gambar sebagai layer operasional peta."
});