define({
  "_widgetLabel": "Imprimir",
  "title": "Título do mapa",
  "format": "Formato",
  "layout": "Layout",
  "settings": "Avançado",
  "labels": "Rótulos",
  "showLabels": "Mostrar rótulos",
  "mapScaleExtent": "Extensão/escala do mapa",
  "preserve": "Preservar",
  "mapScale": "escala do mapa",
  "mapExtent": "extensão do mapa",
  "forceScale": "Forçar escala",
  "getCurrentScale": "atual",
  "mapMetadata": "Metadados do layout",
  "author": "Autor",
  "copyright": "Direitos Autorais",
  "fullLayoutOptions": "Opções completas de layout",
  "scaleBarUnitsMetric": "Unidades métricas da barra de escala",
  "scaleBarUnitsNonMetric": "Unidades não métricas da barra de escala",
  "unitsMiles": "Milhas",
  "unitsKilometers": "Quilômetros",
  "unitsMeters": "Metros",
  "unitsFeet": "Pés",
  "unitsYards": "Jardas",
  "unitsNauticalMiles": "Milhas náuticas",
  "lncludeLegend": "Incluir legenda",
  "printQualityOptions": "Qualidade da impressão",
  "dpi": "DPI",
  "mapOnlyOptions": "Tamanho MAP_ONLY",
  "width": "Largura (px)",
  "height": "Altura (px)",
  "print": "Imprimir",
  "clearList": "Limpar impressões",
  "creatingPrint": "Criando impressão",
  "printError": "Erro, tente novamente"
});