define({
  "taskUrl": "URL Tugas",
  "serviceURLPlaceholder": "Harap masukkan URL tugas Geoprocessing",
  "layerOrder": "Urutan Layer",
  "defaultValue": "Nilai default",
  "inputFeatureBy": "Input fitur menurut",
  "renderer": "Perender",
  "displayType": "Tipe tampilan",
  "helpUrl": "URL Bantuan",
  "useResultMapService": "Lihat hasil dengan map service",
  "drawOnMap": "Menggambar secara interaktif pada peta",
  "selectLayer": "Memilih sebuah layer dari peta",
  "shareResults": "Tambahkan hasil sebagai layer operasional",
  "setTask": "Atur",
  "setTaskTitle": "Atur tugas GP",
  "enablePopup": "Aktifkan popup",
  "unSupportGeometryType": "Tidak dapat menetapkan perender karena tipe geometri tidak diketahui.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Unggah file",
  "selectFileToUpload": "Pilih file...",
  "rasterFormat": "Format data Raster",
  "noFileSelected": "Tidak ada file yang dipilih!",
  "uploadSuccess": "Berhasil mengunggah file!",
  "showLayerContent": "Tampilkan konten layer",
  "urlPlaceholder": "URL rangkaian fitur",
  "useShapefile": "Gunakan shapefile dalam sistem file lokal",
  "allowToExport": "Izinkan untuk mengekspor hasil",
  "useDynamicSchema": "Output mungkin menggunakan skema yang berbeda, gunakan skema dinamik selain skema yang sudah ada.",
  "useCurrentMapExtent": "Gunakan jangkauan peta saat ini",
  "ignoreOutput": "Abaikan output ini",
  "turnOffOutput": "Matikan layer ini secara default"
});