define({
  "showArcgisBasemaps": "Zahrnout podkladové mapy portálu",
  "add": "Kliknutím přidáte novou podkladovou mapu.",
  "edit": "Vlastnosti",
  "titlePH": "Název podkladové mapy",
  "thumbnailHint": "Kliknutím na obrázek jej aktualizujete.",
  "urlPH": "Adresa URL vrstvy",
  "addlayer": "Přidat podkladovou mapu",
  "warning": "Nesprávný vstup",
  "save": "Zpět a uložit",
  "back": "Zpět a zrušit",
  "addUrl": "Přidat URL",
  "autoCheck": "Automatická kontrola",
  "checking": "Probíhá kontrola…",
  "result": "Úspěšně uloženo",
  "spError": "Všechny podkladové mapy přidané do galerie musí mít stejný souřadnicový systém.",
  "invalidTitle1": "Podkladová mapa '",
  "invalidTitle2": "' již existuje. Zvolte jiný název.",
  "invalidBasemapUrl1": "Vrstvu tohoto typu nelze použít jako podkladovou mapu.",
  "invalidBasemapUrl2": "Souřadnicový systém přidávané podkladové mapy se liší od souřadnicového systému současné mapy.",
  "addBaselayer": "Přidat vrstvu podkladové mapy",
  "repectOnline": "Vždy synchronizovat s nastavením galerie podkladových map organizace",
  "customBasemap": "Konfigurovat vlastní podkladové mapy",
  "basemapTips": "Chcete-li přidat podkladové mapy, klikněte na možnost „${import}“ nebo „${createNew)“.",
  "importBasemap": "Importovat",
  "createBasemap": "Vytvořit nový",
  "importTitle": "Importovat podkladové mapy",
  "createTitle": "Nová podkladová mapa",
  "selectGroupTip": "Umožňuje vybrat skupinu, jejíž webové mapy lze použít jako podkladové mapy.",
  "noBasemaps": "K dispozici nejsou žádné podkladové mapy.",
  "defaultGroup": "Výchozí nastavení Esri",
  "defaultOrgGroup": "Výchozí nastavení organizace",
  "warningTitle": "Varování",
  "confirmDelete": "Chcete odstranit vybrané podkladové mapy?",
  "noBasemapAvailable": "K dispozici nejsou žádné podkladové mapy, protože všechny podkladové mapy používají jiný souřadnicový systém nebo schéma dlaždic než současná mapa."
});