define({
  "addDistance": "Thêm đơn vị độ dài",
  "addArea": "Thêm đơn vị diện tích",
  "label": "Nhãn",
  "abbr": "Viết tắt",
  "conversion": "Chuyển đổi",
  "actions": "Các hành động",
  "areaUnits": "Đơn vị diện tích",
  "distanceUnits": "Đơn vị độ dài",
  "kilometers": "Kilômét",
  "miles": "Dặm",
  "meters": "Mét",
  "feet": "Feet",
  "yards": "Thước",
  "nauticalmiles": "Hải lý",
  "squareKilometers": "Kilômét vuông",
  "squareMiles": "Dặm vuông",
  "acres": "Mẫu Anh",
  "hectares": "Hecta",
  "squareMeters": "Mét vuông",
  "squareFeet": "Feet vuông",
  "squareYards": "Thước vuông",
  "distance": "Khoảng cách",
  "area": "Diện tích",
  "kilometersAbbreviation": "km",
  "milesAbbreviation": "mi",
  "metersAbbreviation": "m",
  "feetAbbreviation": "ft",
  "yardsAbbreviation": "yd",
  "nauticalmilesAbbreviation": "nm",
  "squareKilometersAbbreviation": "km2",
  "squareMilesAbbreviation": "mi2",
  "acresAbbreviation": "ac",
  "hectaresAbbreviation": "ha",
  "squareMetersAbbreviation": "m2",
  "squareFeetAbbreviation": "ft2",
  "squareYardsAbbreviation": "yd2",
  "defineUnits": "Xác định đơn vị đo lường.",
  "operationalLayer": "Thêm hình vẽ làm lớp hoạt động của bản đồ."
});