define({
  "showArcgisBasemaps": "Incluir mapas base do Portal",
  "add": "Clique para adicionar um novo mapa base",
  "edit": "Propriedades",
  "titlePH": "Título do mapa base",
  "thumbnailHint": "Clique na imagem para atualizar",
  "urlPH": "URL da Camada",
  "addlayer": "Adicionar mapa base",
  "warning": "Entrada incorreta",
  "save": "Retroceder e guardar",
  "back": "Retroceder e cancelar",
  "addUrl": "Adicionar URL",
  "autoCheck": "Verificar automaticamente",
  "checking": "Verificando...",
  "result": "Guardado com sucesso",
  "spError": "Todos os mapas base adicionados à galeria tem de ter a mesma referência espacial.",
  "invalidTitle1": "Um mapa base '",
  "invalidTitle2": "' já existe. Por favor, escolha outro título.",
  "invalidBasemapUrl1": "Este tipo de camada não pode ser utilizado como mapa base.",
  "invalidBasemapUrl2": "O mapa base que está a adicionar tem uma referência espacial diferente do mapa actual.",
  "addBaselayer": "Adicionar camada de mapa base",
  "repectOnline": "Sincronizar sempre com as definições de Galeria de Mapas Base da organização",
  "customBasemap": "Configurar mapas base personalizados",
  "basemapTips": "Clique em \"${import}\" ou em \"${createNew}\" para adicionar mapas base.",
  "importBasemap": "Importar",
  "createBasemap": "Criar novo",
  "importTitle": "Importar mapas base",
  "createTitle": "Novo mapa base",
  "selectGroupTip": "Selecione um grupo cujos mapas web podem ser utilizados como mapas base.",
  "noBasemaps": "Não existem mapas base.",
  "defaultGroup": "Padrão da Esri",
  "defaultOrgGroup": "Padrão da organização",
  "warningTitle": "Aviso",
  "confirmDelete": "Pretende eliminar os mapas base selecionados?",
  "noBasemapAvailable": "Não existem mapas base disponíveis, já que todos os mapas base têm referências espaciais ou esquemas de mosaicos diferentes em relação ao atual mapa."
});