define({
  "showArcgisBasemaps": "Inkludera portalbaskartor",
  "add": "Klicka om du vill lägga till en ny baskarta",
  "edit": "Egenskaper",
  "titlePH": "Baskartans titel",
  "thumbnailHint": "Klicka på bilden för att uppdatera den",
  "urlPH": "Lager-URL",
  "addlayer": "Lägg till baskarta",
  "warning": "Felaktiga indata",
  "save": "Gå tillbaka och spara",
  "back": "Gå tillbaka och avbryt",
  "addUrl": "Lägg till URL",
  "autoCheck": "Automatisk kontroll",
  "checking": "Kontrollerar ...",
  "result": "Sparad",
  "spError": "Alla baskartor som läggs till i galleriet måste ha samma geografiska referens.",
  "invalidTitle1": "Baskartan '",
  "invalidTitle2": "' finns redan. Välj en annan titel.",
  "invalidBasemapUrl1": "Den här typen av lager går inte att använda som baskarta.",
  "invalidBasemapUrl2": "Den baskarta du lägger till har en annan geografisk referens än den aktuella kartan.",
  "addBaselayer": "Lägg till baskartlager",
  "repectOnline": "Synkronisera alltid med organisationens baskartgalleriinställning",
  "customBasemap": "Konfigurera anpassade baskartor",
  "basemapTips": "Klicka på ${import} eller ${createNew} för att lägga till baskartor.",
  "importBasemap": "Importera",
  "createBasemap": "Skapa ny",
  "importTitle": "Importera baskartor",
  "createTitle": "Ny baskarta",
  "selectGroupTip": "Välj en grupp vars webbkartor kan användas som baskartor.",
  "noBasemaps": "Inga baskartor.",
  "defaultGroup": "Esri-standard",
  "defaultOrgGroup": "Organisationsstandard",
  "warningTitle": "Varning",
  "confirmDelete": "Vill du radera de markerade baskartorna?",
  "noBasemapAvailable": "Det finns inga tillgängliga baskartor eftersom alla baskartor har en annan geografisk referens eller ett annat tiling-schema än den aktuella kartan."
});