define({
  "_widgetLabel": "地理處理",
  "_featureAction_ReceiveFeatureSet": "設定輸入 ",
  "requiredInfo": "是必要的。",
  "drawnOnMap": "結果繪製在地圖上。",
  "noToolConfig": "無可用的預配置地理處理任務。",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "上傳檔案",
  "selectFileToUpload": "選擇檔案...",
  "rasterFormat": "光柵資料格式",
  "noFileSelected": "未選擇任何檔案!",
  "uploadSuccess": "檔案上傳成功!",
  "showLayerContent": "顯示圖層內容",
  "invalidUrl": "圖徵服務 url 無效",
  "urlPlaceholder": "圖徵設定 URL",
  "addShapefile": "新增 Shapefile",
  "generateShapefileError": "產生 shapefile 錯誤，請檢查: ",
  "cleared": "已清除結果。",
  "enlargeView": "放大視圖",
  "exportOutput": "匯出",
  "emptyResult": "結果為空。",
  "useSelectedFeatureset": "使用結果圖徵。",
  "closeSelectedFeatureset": "清除和使用配置的輸入選項。"
});