define({
  "_widgetLabel": "Geoprocessing",
  "_featureAction_ReceiveFeatureSet": "Nastavit jako vstup pro ",
  "requiredInfo": "je vyžadováno.",
  "drawnOnMap": "Výsledek je vykreslen na mapě.",
  "noToolConfig": "Není k dispozici žádná geoprocessingová úloha.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Nahrát soubor",
  "selectFileToUpload": "Vybrat soubor…",
  "rasterFormat": "Formát rastrových dat",
  "noFileSelected": "Nebyl vybrán žádný soubor.",
  "uploadSuccess": "Nahrání souboru proběhlo úspěšně.",
  "showLayerContent": "Zobrazit obsah vrstvy",
  "invalidUrl": "Neplatná adresa URL Feature Service",
  "urlPlaceholder": "adresa URL sady prvků",
  "addShapefile": "Přidat shapefile",
  "generateShapefileError": "Byla vygenerována chyba shapefile, prosím zkontrolujte: ",
  "cleared": "Výsledek byl vymazán.",
  "enlargeView": "Zvětšit zobrazení",
  "exportOutput": "Exportovat",
  "emptyResult": "Výsledek je prázdný.",
  "useSelectedFeatureset": "Umožňuje použít výsledné prvky.",
  "closeSelectedFeatureset": "Vymaže výběr a použije konfigurovanou možnost vstupu.",
  "currentMapExtent": "Aktuální rozsah mapy"
});