define({
  "_widgetLabel": "ड्रा",
  "selectDrawMode": "ड्रा मोड का चयन करें",
  "clear": "हटाएं",
  "point": "बिन्दु",
  "line": "रेखा",
  "polyline": "बहुरेखा",
  "freehandPolyline": "मुक्तहस्त बहुरेखा",
  "triangle": "त्रिभुज",
  "extent": "लिफ़ाफ़ा",
  "circle": "वृत्त",
  "ellipse": "अंडाकार",
  "polygon": "बहुभुज",
  "freehandPolygon": "मुक्तहस्त बहुभुज",
  "text": "पाठ",
  "style": "शैली",
  "alpha": "पारदर्शिता",
  "width": "चौड़ाई",
  "size": "आकार",
  "color": "रंग",
  "markerColor": "मार्कर का रंग",
  "outlineColor": "बाह्यरेखा का रंग",
  "lineColor": "रेखा का रंग",
  "fillColor": "रंग भरें",
  "showMeasurements": "माप दिखाएँ",
  "areaUnits": "क्षेत्र इकाइयाँ",
  "distanceUnits": "दूरी की इकाइयां",
  "kilometers": "किलोमीटर",
  "miles": "मील",
  "meters": "मीटर",
  "feet": "फ़ीट",
  "yards": "गज",
  "nauticalmiles": "समुद्री मील",
  "squareKilometers": "वर्ग किलोमीटर",
  "squareMiles": "वर्ग मील",
  "acres": "एकड़",
  "hectares": "हेक्टेयर",
  "squareMeters": "वर्ग मीटर",
  "squareFeet": "वर्ग फीट",
  "squareYards": "वर्ग गज",
  "undo": "पूर्ववत करें",
  "redo": "पुनः करें",
  "results": "परिणाम",
  "points": "बिंदु",
  "lines": "रेखाएं",
  "areas": "क्षेत्रों"
});