define({
  "showArcgisBasemaps": "Įtraukti portalo pagrindo žemėlapius",
  "add": "Paspauskite norėdami pridėti naują pagrindo žemėlapį",
  "edit": "Savybės",
  "titlePH": "Pagrindo žemėlapio pavadinimas",
  "thumbnailHint": "Paspauskite vaizdą norėdami atnaujinti",
  "urlPH": "Sluoksnio URL",
  "addlayer": "Pridėti pagrindo žemėlapį",
  "warning": "Klaidinga įvestis",
  "save": "Atgal ir išsaugoti",
  "back": "Atgal ir atšaukti",
  "addUrl": "Pridėti URL",
  "autoCheck": "Automatinė patikra",
  "checking": "Tikrinama...",
  "result": "Išsaugota sėkmingai",
  "spError": "Visi į galeriją įtraukti pagrindo žemėlapiai privalo būti toje pačioje koordinačių sistemoje.",
  "invalidTitle1": "Pagrindo žemėlapis '",
  "invalidTitle2": "' jau yra. Pasirinkite kitą pavadinimą.",
  "invalidBasemapUrl1": "Šis sluoksnio tipas negali būti naudojamas kaip pagrindo žemėlapis.",
  "invalidBasemapUrl2": "Pagrindo žemėlapis, kurį norite įtraukti, esamame žemėlapyje yra kitoje koordinačių sistemoje.",
  "addBaselayer": "Pridėti pagrindo žemėlapio sluoksnį",
  "repectOnline": "Visada sinchronizuokite su organizacijos pagrindo žemėlapių galerijos parametru",
  "customBasemap": "Konfigūruoti adaptuotus pagrindo žemėlapius",
  "basemapTips": "Paspauskite \"${import}\" arba \"${createNew}\", kad pridėtumėte pagrindo žemėlapių.",
  "importBasemap": "Importuoti",
  "createBasemap": "Sukurti naują",
  "importTitle": "Importuoti pagrindo žemėlapius",
  "createTitle": "Naujas pagrindo žemėlapis",
  "selectGroupTip": "Pasirinkite grupę, kurios internetinius žemėlapius galima naudoti kaip pagrindo žemėlapius.",
  "noBasemaps": "Nėra pagrindo žemėlapių.",
  "defaultGroup": "Esri numatytasis",
  "defaultOrgGroup": "Organizacijos numatytasis",
  "warningTitle": "Įspėjimas",
  "confirmDelete": "Ar norite pašalinti pasirinktus pagrindo žemėlapius?",
  "noBasemapAvailable": "Pagrindo žemėlapių nėra, nes jie visi turi skirtingas koordinačių sistemas arba išklotinių schemas negu esamas žemėlapis."
});