define({
  "taskUrl": "Užduoties URL",
  "serviceURLPlaceholder": "Įveskite geoduomenų apdorojimo užduoties URL",
  "layerOrder": "Sluoksnių tvarka",
  "defaultValue": "Numatytoji reikšmė",
  "inputFeatureBy": "Įvesti elementą pagal",
  "renderer": "Vaizdavimas",
  "displayType": "Rodymo būdas",
  "helpUrl": "Pagalbos URL",
  "useResultMapService": "Peržiūrėti rezultatą naudojant žemėlapio paslaugą",
  "drawOnMap": "Interaktyvus piešimas žemėlapyje",
  "selectLayer": "Sluoksnio iš žemėlapio pasirinkimas",
  "shareResults": "Pridėti rezultatus kaip darbinį sluoksnį",
  "setTask": "Nustatyti",
  "setTaskTitle": "Nustatyti GP užduotį",
  "enablePopup": "Įgalinti informacinį langą",
  "unSupportGeometryType": "Negalima nustatyti vaizdavimo dėl nežinomo geometrijos tipo.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Įkelti failą",
  "selectFileToUpload": "Pasirinkite failą...",
  "rasterFormat": "Rastrinių duomenų formatas",
  "noFileSelected": "Nepasirinktas joks failas!",
  "uploadSuccess": "Failas įkeltas sėkmingai!",
  "showLayerContent": "Rodyti sluoksnio turinį",
  "urlPlaceholder": "elementui nustatytas URL",
  "useShapefile": "Naudoti Shape failą vietinėje failų sistemoje",
  "allowToExport": "Leisti eksportuoti rezultatus",
  "useDynamicSchema": "Išvesties schema gali būti kitokia, naudokite ne iš anksto nustatytą, o dinaminę schemą.",
  "useCurrentMapExtent": "Naudoti esamą žemėlapio aprėptį",
  "ignoreOutput": "Nepaisyti šios išvesties",
  "turnOffOutput": "Išjungti šį sluoksnį pagal numatytuosius nustatymus"
});