define({
  "addDistance": "Pievienot garuma mērvienību",
  "addArea": "Pievienot laukuma mērvienību",
  "label": "Kartes teksts",
  "abbr": "Saīsinājums",
  "conversion": "Konvertācija",
  "actions": "Darbības",
  "areaUnits": "Laukuma mērvienības",
  "distanceUnits": "Garuma mērvienības",
  "kilometers": "Kilometri",
  "miles": "Jūdzes",
  "meters": "Metri",
  "feet": "Pēdas",
  "yards": "Jardi",
  "nauticalmiles": "Jūras jūdzes",
  "squareKilometers": "Kvadrātkilometri",
  "squareMiles": "Kvadrātjūdzes",
  "acres": "Akri",
  "hectares": "Hektāri",
  "squareMeters": "Kvadrātmetri",
  "squareFeet": "Kvadrātpēdas",
  "squareYards": "Kvadrātjardi",
  "distance": "Attālumi",
  "area": "Apgabali",
  "kilometersAbbreviation": "km",
  "milesAbbreviation": "jūdzes",
  "metersAbbreviation": "m",
  "feetAbbreviation": "pēdas",
  "yardsAbbreviation": "jardi",
  "nauticalmilesAbbreviation": "jj",
  "squareKilometersAbbreviation": "kvadrātkilometri",
  "squareMilesAbbreviation": "kvadrātjūdzes",
  "acresAbbreviation": "akri",
  "hectaresAbbreviation": "ha",
  "squareMetersAbbreviation": "kvadrātmetri",
  "squareFeetAbbreviation": "kvadrātpēdas",
  "squareYardsAbbreviation": "kvadrātjardi",
  "defineUnits": "Definējiet mērvienības.",
  "operationalLayer": "Pievienojiet zīmējumu kā kartes darbību slāni."
});