define({
  "_widgetLabel": "지오프로세싱",
  "_featureAction_ReceiveFeatureSet": "다음의 입력으로 설정 ",
  "requiredInfo": "이(가) 필요합니다.",
  "drawnOnMap": "결과가 맵에 그려집니다.",
  "noToolConfig": "미리 구성된 사용 가능한 지오프로세싱 태스크가 없습니다.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "파일 업로드",
  "selectFileToUpload": "파일 선택...",
  "rasterFormat": "래스터 데이터 형식",
  "noFileSelected": "선택한 파일 없음",
  "uploadSuccess": "파일 업로드 완료",
  "showLayerContent": "레이어 콘텐츠 보기",
  "invalidUrl": "잘못된 피처 서비스 URL",
  "urlPlaceholder": "기능 모음 URL",
  "addShapefile": "쉐이프파일 추가",
  "generateShapefileError": "쉐이프파일 생성 오류입니다. 다음을 확인하세요. ",
  "cleared": "결과가 지워졌습니다.",
  "enlargeView": "뷰 확대",
  "exportOutput": "내보내기",
  "emptyResult": "결과가 비어 있습니다.",
  "useSelectedFeatureset": "결과 피처를 사용합니다.",
  "closeSelectedFeatureset": "구성된 입력 옵션을 선택 해제하고 사용합니다.",
  "currentMapExtent": "현재 맵 범위"
});