define({
  "_widgetLabel": "Ispis",
  "title": "Naslov karte",
  "format": "Format",
  "layout": "Izgled",
  "settings": "Napredno",
  "labels": "Oznake",
  "showLabels": "Prikaži oznake",
  "mapScaleExtent": "Mjerilo/obuhvat karte",
  "preserve": "Sačuvaj",
  "mapScale": "mjerilo karte",
  "mapExtent": "obuhvat karte",
  "forceScale": "Zadano mjerilo",
  "getCurrentScale": "trenutačno",
  "mapMetadata": "Metapodaci izgleda",
  "author": "Autor",
  "copyright": "Autorsko pravo",
  "fullLayoutOptions": "Opcije cijelog izgleda",
  "scaleBarUnitsMetric": "Metričke jedinice grafičkog mjerila",
  "scaleBarUnitsNonMetric": "Jedinice grafičkog mjerila koje nisu metričke",
  "unitsMiles": "Milje",
  "unitsKilometers": "Kilometri",
  "unitsMeters": "Metri",
  "unitsFeet": "Stope",
  "unitsYards": "Jardi",
  "unitsNauticalMiles": "Nautičke milje",
  "lncludeLegend": "Uključi legendu",
  "printQualityOptions": "Kvaliteta ispisa",
  "dpi": "DPI",
  "mapOnlyOptions": "Veličina za MAP_ONLY",
  "width": "Širina (px)",
  "height": "Visina (px)",
  "print": "Ispis",
  "clearList": "Izbriši ispise",
  "creatingPrint": "Stvaranje ispisa",
  "printError": "Pogreška, pokušajte ponovno"
});