define({
  "_widgetLabel": "Geoprzetwarzanie",
  "_featureAction_ReceiveFeatureSet": "Ustaw jako wejście ",
  "requiredInfo": "jest wymagane.",
  "drawnOnMap": "Wynik zostaje wyświetlony na mapie.",
  "noToolConfig": "Brak wstępnie skonfigurowanego zadania geoprzetwarzania.",
  "useUrlForGPInput": "Adres URL",
  "useUploadForGPInput": "Wczytaj plik",
  "selectFileToUpload": "Wybierz plik...",
  "rasterFormat": "Format danych wynikowych",
  "noFileSelected": "Nie wybrano pliku!",
  "uploadSuccess": "Pomyślnie przesłano plik!",
  "showLayerContent": "Wyświetl zawartość warstwy",
  "invalidUrl": "Niepoprawny adres URL usługi obiektowej",
  "urlPlaceholder": "adres URL zestawów obiektów",
  "addShapefile": "Dodaj plik shape",
  "generateShapefileError": "Błąd generowania pliku shape, sprawdź: ",
  "cleared": "Wynik został wyczyszczony.",
  "enlargeView": "Powiększ widok",
  "exportOutput": "Eksportuj",
  "emptyResult": "Wynik jest pusty.",
  "useSelectedFeatureset": "Użyj obiektów wynikowych.",
  "closeSelectedFeatureset": "Wyczyść i użyj skonfigurowanej opcji wejścia."
});