define({
  "taskUrl": "URL của tác vụ",
  "serviceURLPlaceholder": "Vui lòng nhập URL của tác vụ Địa xử lý",
  "layerOrder": "Thứ tự lớp",
  "defaultValue": "Giá trị mặc định",
  "inputFeatureBy": "Nhập đối tượng theo",
  "renderer": "Trình kết xuất",
  "displayType": "Loại hiển thị",
  "helpUrl": "URL trợ giúp",
  "useResultMapService": "Xem kết quả với dịch vụ bản đồ",
  "drawOnMap": "Vẽ tương tác trên bản đồ",
  "selectLayer": "Chọn một lớp từ bản đồ",
  "shareResults": "Thêm kết quả như lớp hoạt động",
  "setTask": "Thiết lập",
  "setTaskTitle": "Thiết lập tác vụ GP",
  "enablePopup": "Bật cửa sổ pop-up",
  "unSupportGeometryType": "Không thể thiết lập trình kết xuất vì loại hình học không xác định.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Tải lên tệp",
  "selectFileToUpload": "Chọn tệp...",
  "rasterFormat": "Định dạng dữ liệu raster",
  "noFileSelected": "Không có tệp được chọn!",
  "uploadSuccess": "Tải lên tệp thành công!",
  "showLayerContent": "Hiển thị nội dung lớp",
  "urlPlaceholder": "URL tập hợp đối tượng",
  "useShapefile": "Sử dụng shapefile trong hệ thống tệp cục bộ",
  "allowToExport": "Cho phép xuất kết quả",
  "useDynamicSchema": "Đầu ra có thể có giản đồ khác, hãy sử dụng giản đồ động thay cho giản đồ được định nghĩa trước.",
  "useCurrentMapExtent": "Sử dụng phạm vi bản đồ hiện tại",
  "ignoreOutput": "Bỏ qua kết quả đầu ra này",
  "turnOffOutput": "Tắt lớp này theo mặc định"
});