define({
  "_widgetLabel": "طباعة",
  "title": "عنوان الخريطة",
  "format": "تنسيق",
  "layout": "المخطط",
  "settings": "متقدم",
  "labels": "تسميات",
  "showLabels": "إظهار لافتات التسمية",
  "mapScaleExtent": "مقياس رسم/نطاق الخريطة",
  "preserve": "المحافظة على",
  "mapScale": "مقياس رسم الخريطة",
  "mapExtent": "نطاق الخريطة",
  "forceScale": "مقياس رسم القوى",
  "getCurrentScale": "حالي",
  "mapMetadata": "البيانات التعريفية للتخطيط",
  "author": "المؤلف",
  "copyright": "حقوق النشر",
  "fullLayoutOptions": "خيارات التخطيط الكامل",
  "scaleBarUnitsMetric": "وحدات شريط مقياس الرسم المترية",
  "scaleBarUnitsNonMetric": "وحدات شريط مقياس الرسم غير المترية",
  "unitsMiles": "أميال",
  "unitsKilometers": "كيلومترات",
  "unitsMeters": "مترات",
  "unitsFeet": "قدم",
  "unitsYards": "ياردات",
  "unitsNauticalMiles": "أميال بحرية",
  "lncludeLegend": "تضمين وسيلة الإيضاح",
  "printQualityOptions": "جودة الطباعة",
  "dpi": "DPI",
  "mapOnlyOptions": "حجم MAP_ONLY",
  "width": "العرض (px)",
  "height": "الارتفاع (px)",
  "print": "طباعة",
  "clearList": "مسح الطباعة",
  "creatingPrint": "مسح الطباعة",
  "printError": "خطأ، الرجاء إعادة المحاولة"
});