define({
  "showArcgisBasemaps": "Portal altlık haritalarını dahil et",
  "add": "Yeni bir altlık haritası eklemek için tıklayın",
  "edit": "Özellikler",
  "titlePH": "Altlık haritası başlığı",
  "thumbnailHint": "Güncellemek için resme tıkla",
  "urlPH": "Katman URL'si",
  "addlayer": "Altlık haritası ekle",
  "warning": "Hatalı girdi",
  "save": "Dön ve kaydet",
  "back": "Dön ve iptal et",
  "addUrl": "URL Ekle",
  "autoCheck": "Otomatik denetle",
  "checking": "Denetleniyor...",
  "result": "Başarıyla kaydedildi",
  "spError": "Galeriye eklenen tüm altlık haritalar aynı mekansal başvuruya sahip olmalıdır.",
  "invalidTitle1": "Bir altlık haritası '",
  "invalidTitle2": "' zaten mevcut. Başka bir başlık seçin.",
  "invalidBasemapUrl1": "Bu katman türü altlık haritası olarak kullanılamaz.",
  "invalidBasemapUrl2": "Eklediğiniz altlık haritası geçerli haritadan farklı bir mekansal başvuruya sahip.",
  "addBaselayer": "Altlık haritası katmanı ekle",
  "repectOnline": "Her zaman kuruluşun Altlık Harita Galerisi ayarıyla senkronize edin",
  "customBasemap": "Özel altlık haritaları yapılandırın",
  "basemapTips": "Yeni altlık harita eklemek için \"${import}\" veya \"${createNew}\" öğesine tıklayın.",
  "importBasemap": "İçe Aktar",
  "createBasemap": "Yeni oluştur",
  "importTitle": "Altlık haritaları içe aktar",
  "createTitle": "Yeni altlık haritası",
  "selectGroupTip": "Web haritaları altlık harita olarak kullanılabilen bir grup seçin.",
  "noBasemaps": "Altlık harita yok.",
  "defaultGroup": "Esri varsayılanı",
  "defaultOrgGroup": "Kuruluş varsayılanı",
  "warningTitle": "Uyarı",
  "confirmDelete": "Seçili altlık haritaları silmek istiyor musunuz?",
  "noBasemapAvailable": "Tüm altlık haritalarda geçerli haritadan daha farklı mekansal başvuru veya döşeme şeması olduğundan kullanılabilir altlık harita yok."
});