define({
  "taskUrl": "URL attività",
  "serviceURLPlaceholder": "Immettere l'URL dell'attività di geoprocessing",
  "layerOrder": "Ordine layer",
  "defaultValue": "Valore di default",
  "inputFeatureBy": "Immetti feature per",
  "renderer": "Renderer",
  "displayType": "Tipo visualizzazione",
  "helpUrl": "URL Guida",
  "useResultMapService": "Visualizza il risultato con un map service",
  "drawOnMap": "Disegno interattivo sulla mappa",
  "selectLayer": "Selezione di un layer nella mappa",
  "shareResults": "Aggiungi risultato come layer operativo",
  "setTask": "Imposta",
  "setTaskTitle": "Imposta attività GP",
  "enablePopup": "Abilita popup",
  "unSupportGeometryType": "Tipo di geometria sconosciuto. Impossibile impostare il renderer.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Carica file",
  "selectFileToUpload": "Seleziona file...",
  "rasterFormat": "Formato dati raster",
  "noFileSelected": "Nessun file selezionato.",
  "uploadSuccess": "Caricamento file riuscito.",
  "showLayerContent": "Mostra contenuto layer",
  "urlPlaceholder": "URL insieme di feature",
  "useShapefile": "Usa shapefile nel file system locale",
  "allowToExport": "Consente di esportare i risultati",
  "useDynamicSchema": "Lo schema dell'output può essere diverso; utilizzare lo schema dinamico anziché quello predefinito."
});