define({
  "_widgetLabel": "ジオプロセシング",
  "_featureAction_ReceiveFeatureSet": "次の入力として設定 ",
  "requiredInfo": "は必須です。",
  "drawnOnMap": "結果はマップ上に描画されます。",
  "noToolConfig": "構成済みの使用可能なジオプロセシング タスクがありません。",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "ファイルのアップロード",
  "selectFileToUpload": "ファイルの選択...",
  "rasterFormat": "ラスター データ形式",
  "noFileSelected": "ファイルが選択されませんでした。",
  "uploadSuccess": "ファイルのアップロードに成功しました。",
  "showLayerContent": "レイヤー コンテンツの表示",
  "invalidUrl": "無効なフィーチャ サービス URL",
  "urlPlaceholder": "フィーチャ セット URL",
  "addShapefile": "シェープファイルの追加",
  "generateShapefileError": "シェープファイルの生成でエラーが発生しました。次を確認してください: ",
  "cleared": "結果が消去されました。",
  "enlargeView": "拡大表示",
  "exportOutput": "エクスポート",
  "emptyResult": "結果が空です。",
  "useSelectedFeatureset": "得られたフィーチャを使用します。",
  "closeSelectedFeatureset": "構成済みの入力オプションを消去するか、使用します。"
});