define({
  "_widgetLabel": "Geoprocessing",
  "_featureAction_ReceiveFeatureSet": "ตั้งค่าเป็นข้อมูลตั้งต้นของ ",
  "requiredInfo": "ที่จำเป็น",
  "drawnOnMap": "ผลลัพธ์ถูกวาดลงบนแผนที่",
  "noToolConfig": "ไม่มี การประมวลผลทางภูมิศาสตร์ (Geoprocessing Task) ที่กำหนดไว้ล่วงหน้า",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "อัพโหลดไฟล์",
  "selectFileToUpload": "เลือกไฟล์...",
  "rasterFormat": "รูปแบบข้อมูลราสเตอร์",
  "noFileSelected": "ไม่มีไฟล์ที่ถูกเลือก",
  "uploadSuccess": "อัพโหลดไฟล์สำเร็จ",
  "showLayerContent": "แสดงรายละเอียดของชั้นข้อมูล",
  "invalidUrl": "คุณลักษณะที่ไม่ถูกต้องของ url",
  "urlPlaceholder": "การตั้งค่าคุณลักษณะ URL",
  "addShapefile": "เพิ่ม shapefile",
  "generateShapefileError": "การสร้าง shapefile ล้มเหว กรุณาตรวจสอบ ",
  "cleared": "ผลลัพท์ถูกยกเลิก",
  "enlargeView": "ขยายหน้าต่างในการแสดงผล",
  "exportOutput": "ส่งออก",
  "emptyResult": "ผลที่ได้ว่างเปล่า",
  "useSelectedFeatureset": "ใช้ฟีเจอร์ผลลัพธ์",
  "closeSelectedFeatureset": "ล้าง และใช้ตัวเลือกในการกำหนดค่าอินพุท"
});