define({
  "taskUrl": "URL υπηρεσίας",
  "serviceURLPlaceholder": "Εισαγάγετε το URL της υπηρεσίας γεωεπεξεργασίας",
  "layerOrder": "Διάταξη θεματικών επιπέδων",
  "defaultValue": "Προεπιλεγμένη τιμή",
  "inputFeatureBy": "Καθορισμός στοιχείου εισόδου με",
  "renderer": "Απεικόνιση",
  "displayType": "Τύπος εμφάνισης",
  "helpUrl": "URL βοήθειας",
  "useResultMapService": "Προβολή αποτελέσματος με map service",
  "drawOnMap": "Διαδραστική σχεδίαση στο χάρτη",
  "selectLayer": "Επιλογή θεματικού επιπέδου από τον χάρτη",
  "shareResults": "Προσθήκη αποτελέσματος ως επιχειρησιακό επίπεδο",
  "setTask": "Ορισμός",
  "setTaskTitle": "Ορισμός εργασίας GP",
  "enablePopup": "Ενεργοποίηση αναδυόμενου παραθύρου",
  "unSupportGeometryType": "Δεν είναι δυνατός ο καθορισμός της απεικόνισης λόγω άγνωστου τύπου γεωμετρίας.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Φόρτωση αρχείου",
  "selectFileToUpload": "Επιλογή αρχείου...",
  "rasterFormat": "Μορφότυπος πλεγματικών δεδομένων",
  "noFileSelected": "Δεν επιλέχθηκε αρχείο!",
  "uploadSuccess": "Το αρχείο φορτώθηκε με επιτυχία!",
  "showLayerContent": "Εμφάνιση περιεχομένου θεματικού επιπέδου",
  "urlPlaceholder": "URL συνόλου στοιχείων",
  "useShapefile": "Χρήση shapefile στο τοπικό σύστημα αρχείων",
  "allowToExport": "Να επιτραπεί η εξαγωγή αποτελεσμάτων",
  "useDynamicSchema": "Το σχήμα της εξόδου ενδέχεται να διαφέρει. Χρησιμοποιήστε δυναμικό σχήμα αντί του προκαθορισμένου.",
  "useCurrentMapExtent": "Χρήση τρέχουσας έκτασης χάρτη",
  "ignoreOutput": "Παράβλεψη αυτής της εξόδου",
  "turnOffOutput": "Απενεργοποίηση αυτού του θεματικού επιπέδου με βάση την προεπιλεγμένη ρύθμιση"
});