define({
  "_widgetLabel": "رسم",
  "selectDrawMode": "تحديد وضع الرسم",
  "clear": "مسح",
  "point": "نقطة",
  "line": "الخط",
  "polyline": "متعدد الخطوط",
  "freehandPolyline": "خطوط متصلة مرسومة بخط اليد",
  "triangle": "مثلث",
  "extent": "مُغلف",
  "circle": "دائرة",
  "ellipse": "قطع ناقص",
  "polygon": "مضلع",
  "freehandPolygon": "مضلع يدوي",
  "text": "النص",
  "style": "نمط",
  "alpha": "معدل الشفافية:",
  "width": "العرض",
  "size": "الحجم",
  "color": "لون",
  "markerColor": "لون العلامة",
  "outlineColor": "لون المخطط",
  "lineColor": "لون الخط",
  "fillColor": "تعبئة اللون",
  "showMeasurements": "إظهار القياسات",
  "areaUnits": "وحدات المنطقة",
  "distanceUnits": "وحدات المسافة",
  "kilometers": "كيلومترات",
  "miles": "أميال",
  "meters": "مترات",
  "feet": "قدم",
  "yards": "ياردات",
  "nauticalmiles": "أميال بحرية",
  "squareKilometers": "كيلو مترات مربعة",
  "squareMiles": "أميال مربعة",
  "acres": "فدان",
  "hectares": "هكتار",
  "squareMeters": "أمتار مربعة",
  "squareFeet": "قدم مربع",
  "squareYards": "ياردات مربعة",
  "undo": "تراجع",
  "redo": "تراجع",
  "results": "نتائج",
  "points": "النقاط",
  "lines": "خطوط",
  "areas": "مساحات"
});