define({
  "addDistance": "Dodaj jedinicu duljine",
  "addArea": "Dodaj površinsku jedinicu",
  "label": "Oznaka",
  "abbr": "Kratica",
  "conversion": "Pretvaranje",
  "actions": "Radnje",
  "areaUnits": "Površinske jedinice",
  "distanceUnits": "Jedinice duljine",
  "kilometers": "Kilometri",
  "miles": "Milje",
  "meters": "Metri",
  "feet": "Stope",
  "yards": "Jardi",
  "nauticalmiles": "Nautičke milje",
  "squareKilometers": "Kvadratni kilometri",
  "squareMiles": "Kvadratne milje",
  "acres": "Jutra",
  "hectares": "Hektari",
  "squareMeters": "Kvadratni metri",
  "squareFeet": "Kvadratne stope",
  "squareYards": "Kvadratni jardi",
  "distance": "Udaljenosti",
  "area": "Područja",
  "kilometersAbbreviation": "km",
  "milesAbbreviation": "mi",
  "metersAbbreviation": "m",
  "feetAbbreviation": "ft",
  "yardsAbbreviation": "yd",
  "nauticalmilesAbbreviation": "nm",
  "squareKilometersAbbreviation": "kvadr. km",
  "squareMilesAbbreviation": "kvadr. mi",
  "acresAbbreviation": "ac",
  "hectaresAbbreviation": "ha",
  "squareMetersAbbreviation": "kvadr. m",
  "squareFeetAbbreviation": "kvadr. ft",
  "squareYardsAbbreviation": "kvadr. yd",
  "defineUnits": "Definirajte mjerne jedinice.",
  "operationalLayer": "Dodajte crtež kao operativni sloj karte."
});