define({
  "_widgetLabel": "Geoprocessing",
  "_featureAction_ReceiveFeatureSet": "Atur sebagai input dari ",
  "requiredInfo": "diperlukan.",
  "drawnOnMap": "Hasil tersebut digambarkan pada peta.",
  "noToolConfig": "Tidak tersedia tugas geoprocessing yang dikonfigurasikan sebelumnya.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Unggah file",
  "selectFileToUpload": "Pilih file...",
  "rasterFormat": "Format data Raster",
  "noFileSelected": "Tidak ada file yang dipilih!",
  "uploadSuccess": "Berhasil mengunggah file!",
  "showLayerContent": "Tampilkan konten layer",
  "invalidUrl": "URL feature service tidak valid",
  "urlPlaceholder": "URL rangkaian fitur",
  "addShapefile": "Tambahkan Shapefile",
  "generateShapefileError": "Kesalahan membuat shapefile, harap periksa: ",
  "cleared": "Hasil sudah dibersihkan.",
  "enlargeView": "Perbesar tampilan",
  "exportOutput": "Ekspor",
  "emptyResult": "Hasil tersebut kosong.",
  "useSelectedFeatureset": "Gunakan fitur yang dihasilkan.",
  "closeSelectedFeatureset": "Bersihkan dan gunakan opsi input yang dikonfigurasikan."
});