define({
  "showArcgisBasemaps": "Iekļaut portāla pamatkartes",
  "add": "Noklikšķiniet, lai pievienotu jaunu pamatkarti",
  "edit": "Īpašības",
  "titlePH": "Pamatkartes nosaukums",
  "thumbnailHint": "Noklikšķiniet uz attēla, lai atjauninātu",
  "urlPH": "Slāņa URL",
  "addlayer": "Pievienot pamatkarti",
  "warning": "Nepareiza ievade",
  "save": "Atgriezties un saglabāt",
  "back": "Atgriezties un atcelt",
  "addUrl": "Pievienot URL",
  "autoCheck": "Automātiskā pārbaude",
  "checking": "Pārbaude...",
  "result": "Saglabāšana sekmīga",
  "spError": "Visām galerijai pievienotajām pamatkartēm ir jābūt vienām un tām pašām telpiskajām atskaitēm.",
  "invalidTitle1": "Pamatkarte '",
  "invalidTitle2": "' jau pastāv. Lūdzu, izvēlieties citu nosaukumu.",
  "invalidBasemapUrl1": "Šo slāņa tipu nevar izmantot kā pamatkarti.",
  "invalidBasemapUrl2": "Pamatkartei, kas pašlaik tiek pievienota, telpiskā atskaite atšķiras no pašreizējās kartes.",
  "addBaselayer": "Pievienot pamatkartes slāni",
  "repectOnline": "Vienmēr sinhronizēt ar organizācijas pamatkartes galerijas iestatījumu",
  "customBasemap": "Konfigurēt pielāgotas pamatkartes",
  "basemapTips": "Lai pievienotu pamatkartes, noklikšķiniet uz “${import}” vai “${createNew}”.",
  "importBasemap": "Importēt",
  "createBasemap": "Izveidot jaunu",
  "importTitle": "Importēt pamatkartes",
  "createTitle": "Jauna pamatkarte",
  "selectGroupTip": "Atlasiet grupu, kuras tīmekļa kartes var izmantot kā pamatkartes.",
  "noBasemaps": "Nav nevienas pamatkartes.",
  "defaultGroup": "Esri noklusējums",
  "defaultOrgGroup": "Organizācijas noklusējums",
  "warningTitle": "Brīdinājums",
  "confirmDelete": "Vai vēlaties dzēst izvēlētās pamatkartes?",
  "noBasemapAvailable": "Nav pieejama neviena pamatkarte, jo visu pamatkaršu telpiskās atskaites vai mozaīku shēmas atšķiras no pašreizējās kartes."
});