define({
  "_widgetLabel": "Yazdır",
  "title": "Harita başlığı",
  "format": "Biçim",
  "layout": "Düzen",
  "settings": "Gelişmiş",
  "labels": "Etiketler",
  "showLabels": "Etiketleri göster",
  "mapScaleExtent": "Harita ölçeği/yayılımı",
  "preserve": "Koru",
  "mapScale": "harita ölçeği",
  "mapExtent": "harita yayılımı",
  "forceScale": "Ölçeği zorla",
  "getCurrentScale": "mevcut",
  "mapMetadata": "Düzen meta verisi",
  "author": "Yazar",
  "copyright": "Telif Hakkı",
  "fullLayoutOptions": "Tam düzen seçenekleri",
  "scaleBarUnitsMetric": "Ölçek çubuğu birimi, metrik",
  "scaleBarUnitsNonMetric": "Ölçek çubuğu birimi, metrik olmayan",
  "unitsMiles": "Mil",
  "unitsKilometers": "Kilometre",
  "unitsMeters": "Metre",
  "unitsFeet": "Fit",
  "unitsYards": "Yarda",
  "unitsNauticalMiles": "Deniz mili",
  "lncludeLegend": "Gösterim ekle",
  "printQualityOptions": "Baskı kalitesi",
  "dpi": "DPI",
  "mapOnlyOptions": "MAP_ONLY boyutu",
  "width": "Genişlik (px)",
  "height": "Yükseklik (px)",
  "print": "Yazdır",
  "clearList": "Baskıları temizle",
  "creatingPrint": "Baskı oluşturuluyor",
  "printError": "Hata, yeniden deneyin"
});