define({
  "showArcgisBasemaps": "Portaal-basiskaarten opnemen",
  "add": "Klik om een nieuwe basiskaart toe te voegen",
  "edit": "Eigenschappen",
  "titlePH": "Titel van basiskaart",
  "thumbnailHint": "Klik op de afbeelding om deze te bewerken",
  "urlPH": "Laag-URL",
  "addlayer": "Basiskaart toevoegen",
  "warning": "Onjuiste invoer",
  "save": "Terug en opslaan",
  "back": "Terug en annuleren",
  "addUrl": "URL toevoegen",
  "autoCheck": "Automatisch controleren",
  "checking": "Controleren...",
  "result": "Opslaan is gelukt",
  "spError": "Alle basiskaarten die aan de galerij zijn toegevoegd, moeten dezelfde ruimtelijke referentie hebben.",
  "invalidTitle1": "Een basiskaart '",
  "invalidTitle2": "' bestaat al. Kies een andere titel.",
  "invalidBasemapUrl1": "Dit laagtype kan niet worden gebruikt als een basiskaart.",
  "invalidBasemapUrl2": "De basiskaart die u toevoegt heeft een andere ruimtelijke referentie dan de huidige kaart.",
  "addBaselayer": "Basiskaartlaag toevoegen",
  "repectOnline": "Altijd synchroniseren met de Basemap Gallery-instelling van de organisatie",
  "customBasemap": "Aangepaste basiskaarten configureren",
  "basemapTips": "Klik op \"${import}\" of \"${createNew}\" om basemaps toe te voegen.",
  "importBasemap": "Importeren",
  "createBasemap": "Maak nieuwe",
  "importTitle": "Basiskaarten importeren",
  "createTitle": "Nieuwe basiskaart",
  "selectGroupTip": "Selecteer een groep waarvan de webmaps kunnen worden gebruikt als basiskaarten.",
  "noBasemaps": "Geen basiskaarten.",
  "defaultGroup": "Esri standaard",
  "defaultOrgGroup": "Organisatiestandaard",
  "warningTitle": "Waarschuwing",
  "confirmDelete": "Wilt u geselecteerde basiskaarten verwijderen?",
  "noBasemapAvailable": "Er zijn geen basiskaarten beschikbaar omdat alle basiskaarten een verschillende ruimtelijke referentie of tileschema hebben ten opzichte van de huidige kaart."
});