define({
  "_widgetLabel": "Geoprocesare",
  "_featureAction_ReceiveFeatureSet": "Setare ca intrare pentru ",
  "requiredInfo": "este obligatoriu.",
  "drawnOnMap": "Rezultatul este figurat pe hartă.",
  "noToolConfig": "Nu este disponibilă nicio operaţie de geoprocesare preconfigurată.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Încărcare fişier",
  "selectFileToUpload": "Selectare fişier...",
  "rasterFormat": "Format date raster",
  "noFileSelected": "Niciun fişier selectat!",
  "uploadSuccess": "Încărcare fişier reuşită!",
  "showLayerContent": "Afişare conţinut strat tematic",
  "invalidUrl": "URL serviciu de obiecte spaţiale nevalid",
  "urlPlaceholder": "URL set de obiecte spaţiale",
  "addShapefile": "Adăugare Shapefile",
  "generateShapefileError": "Generare eroare shapefile, vă rugăm să verificaţi: ",
  "cleared": "Rezultatul a fost şters.",
  "enlargeView": "Lărgire vizualizare",
  "exportOutput": "Export",
  "emptyResult": "Rezultatul este gol.",
  "useSelectedFeatureset": "Utilizaţi obiectele spaţiale rezultate.",
  "closeSelectedFeatureset": "Ştergeţi şi utilizaţi opţiunea de introducere configurată."
});