define({
  "_widgetLabel": "Gambar",
  "selectDrawMode": "Pilih mode gambar",
  "clear": "Kosongkan",
  "point": "Titik",
  "line": "Garis",
  "polyline": "Polyline",
  "freehandPolyline": "Polyline bebas",
  "triangle": "Segitiga",
  "extent": "Amplop",
  "circle": "Lingkaran",
  "ellipse": "Elips",
  "polygon": "Poligon",
  "freehandPolygon": "Poligon bebas",
  "text": "Teks",
  "style": "Ragam",
  "alpha": "Transparansi",
  "width": "Lebar",
  "size": "Ukuran",
  "color": "Warna",
  "markerColor": "Warna penanda",
  "outlineColor": "Warna kerangka",
  "lineColor": "Warna garis",
  "fillColor": "Warna isi",
  "showMeasurements": "Tampilkan pengukuran",
  "areaUnits": "Unit area",
  "distanceUnits": "Unit jarak",
  "kilometers": "Kilometer",
  "miles": "Mil",
  "meters": "Meter",
  "feet": "Kaki",
  "yards": "Yard",
  "nauticalmiles": "Mil laut",
  "squareKilometers": "Kilometer persegi",
  "squareMiles": "Mil persegi",
  "acres": "Acre",
  "hectares": "Hektare",
  "squareMeters": "Meter persegi",
  "squareFeet": "Kaki persegi",
  "squareYards": "Yard persegi",
  "undo": "Urung",
  "redo": "Ulangi",
  "results": "Hasil",
  "points": "Titik",
  "lines": "Garis",
  "areas": "Area"
});