define({
  "showArcgisBasemaps": "Grundkarten des Portals einbeziehen",
  "add": "Zum Hinzufügen einer neuen Grundkarte klicken",
  "edit": "Eigenschaften",
  "titlePH": "Titel der Grundkarte",
  "thumbnailHint": "Zum Aktualisieren auf das Bild klicken",
  "urlPH": "Layer-URL",
  "addlayer": "Grundkarte hinzufügen",
  "warning": "Falsche Eingabe",
  "save": "Zurück und Speichern",
  "back": "Zurück und Abbrechen",
  "addUrl": "URL hinzufügen",
  "autoCheck": "Automatisch überprüfen",
  "checking": "Wird überprüft...",
  "result": "Erfolgreich gespeichert",
  "spError": "Alle Grundkarten, die der Galerie hinzugefügt wurden, müssen denselben Raumbezug aufweisen.",
  "invalidTitle1": "Die Grundkarte '",
  "invalidTitle2": "' ist bereits vorhanden. Wählen Sie einen anderen Titel aus.",
  "invalidBasemapUrl1": "Dieser Layer-Typ kann nicht als Grundkarte verwendet werden.",
  "invalidBasemapUrl2": "Die Grundkarte, die Sie hinzufügen, weist einen anderen Raumbezug als die aktuelle Karte auf.",
  "addBaselayer": "Grundkarten-Layer hinzufügen",
  "repectOnline": "Immer mit der Einstellung der Grundkarten-Galerie der Organisation synchronisieren",
  "customBasemap": "Benutzerdefinierte Grundkarten konfigurieren",
  "basemapTips": "Klicken Sie auf \"${import}\" oder \"${createNew}\", um Grundkarten hinzuzufügen.",
  "importBasemap": "Importieren",
  "createBasemap": "Neue erstellen",
  "importTitle": "Grundkarten importieren",
  "createTitle": "Neue Grundkarte",
  "selectGroupTip": "Wählen Sie eine Gruppe aus, deren Webkarten als Grundkarten verwendet werden können.",
  "noBasemaps": "Keine Grundkarten.",
  "defaultGroup": "Esri Standard",
  "defaultOrgGroup": "Standard der Organisation",
  "warningTitle": "Warnung",
  "confirmDelete": "Möchten Sie die gewählten Grundkarten löschen?",
  "noBasemapAvailable": "Es sind keine Grundkarten verfügbar, da alle Grundkarten einen anderen Raumbezug oder ein anderes Kachelschema aufweisen als die aktuelle Karte."
});