define({
  "_widgetLabel": "שרטוט",
  "selectDrawMode": "בחר מצב שרטוט",
  "clear": "נקה",
  "point": "נקודה",
  "line": "קו",
  "polyline": "פולי קו",
  "freehandPolyline": "קו בשרטוט חופשי",
  "triangle": "משולש",
  "extent": "מעטפה",
  "circle": "מעגל",
  "ellipse": "אליפסה",
  "polygon": "פוליגון",
  "freehandPolygon": "פוליגון בשרטוט חופשי",
  "text": "טקסט",
  "style": "סגנון",
  "alpha": "שקיפות",
  "width": "רוחב",
  "size": "גודל",
  "color": "צבע",
  "markerColor": "צבע סמן",
  "outlineColor": "צבע קו תיחום",
  "lineColor": "צבע קו",
  "fillColor": "צבע מילוי",
  "showMeasurements": "הצג מידות",
  "areaUnits": "יחידות שטח",
  "distanceUnits": "יחידות מרחק",
  "kilometers": "קילומטרים",
  "miles": "מיילים",
  "meters": "מטרים",
  "feet": "רגל",
  "yards": "יארד",
  "nauticalmiles": "מיילים ימיים",
  "squareKilometers": "קילומטרים רבועים",
  "squareMiles": "מיילים רבועים",
  "acres": "אקרים",
  "hectares": "הקטרים",
  "squareMeters": "מטרים רבועים",
  "squareFeet": "רגל רבוע",
  "squareYards": "יארדים רבועים",
  "undo": "בטל",
  "redo": "בצע מחדש",
  "results": "תוצאות",
  "points": "נקודות",
  "lines": "קווים",
  "areas": "שטחים"
});