define({
  "_widgetLabel": "Geobearbetning",
  "_featureAction_ReceiveFeatureSet": "Ange som indata från ",
  "requiredInfo": "är obligatoriskt.",
  "drawnOnMap": "Resultatet ritas på kartan.",
  "noToolConfig": "Ingen förkonfigurerad geobearbetningsåtgärd är tillgänglig.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Överför fil",
  "selectFileToUpload": "Välj fil ...",
  "rasterFormat": "Rasterdataformat",
  "noFileSelected": "Ingen fil har valts!",
  "uploadSuccess": "Filen har överförts!",
  "showLayerContent": "Visa lagrets innehåll",
  "invalidUrl": "Ogiltig URL för geoobjektstjänsten.",
  "urlPlaceholder": "URL till geoobjektsuppsättning",
  "addShapefile": "Lägg till shapefil",
  "generateShapefileError": "Fel när shapefilen skapades. Kontrollera: ",
  "cleared": "Resultaten har rensats.",
  "enlargeView": "Förstora vy",
  "exportOutput": "Exportera",
  "emptyResult": "Resultatet är tomt.",
  "useSelectedFeatureset": "Använd resultatgeoobjekten.",
  "closeSelectedFeatureset": "Rensa och använd det konfigurerade indataalternativet.",
  "currentMapExtent": "Aktuell kartutbredning"
});