define({
  "_widgetLabel": "Geoprocesiranje",
  "_featureAction_ReceiveFeatureSet": "Podesi kao unos od ",
  "requiredInfo": "je obavezno.",
  "drawnOnMap": "Rezultat je nacrtan na mapi.",
  "noToolConfig": "Nema dostupnih unapred konfigurisanih zadataka geoprocesiranja.",
  "useUrlForGPInput": "URL adresa",
  "useUploadForGPInput": "Otpremi datoteku",
  "selectFileToUpload": "Izaberite datoteku...",
  "rasterFormat": "Format rasterskih podataka",
  "noFileSelected": "Nema izabrane datoteke!",
  "uploadSuccess": "Uspešno otpremanje datoteke!",
  "showLayerContent": "Prikaži sadržaj sloja",
  "invalidUrl": "Nevažeća URL adresa servisa geoobjekata",
  "urlPlaceholder": "URL adresa seta geoobjekata",
  "addShapefile": "Dodaj datoteku „shapefile“",
  "generateShapefileError": "Generiši grešku datoteke „shapefile“, proverite: ",
  "cleared": "Rezultat je obrisan.",
  "enlargeView": "Uveličaj prikaz",
  "exportOutput": "Izvezi",
  "emptyResult": "Rezultat je prazan.",
  "useSelectedFeatureset": "Koristite rezultujući geoobjekat/geoobjekte.",
  "closeSelectedFeatureset": "Obrišite i koristite konfigurisanu opciju unosa.",
  "currentMapExtent": "Trenutni obuhvat mape"
});