define({
  "taskUrl": "URL de la tâche",
  "serviceURLPlaceholder": "Saisissez l’URL de la tâche de géotraitement",
  "layerOrder": "Ordre des couches",
  "defaultValue": "Valeur par défaut",
  "inputFeatureBy": "Saisir l'entité par",
  "renderer": "Représentation",
  "displayType": "Type d’affichage",
  "helpUrl": "URL de l’aide",
  "useResultMapService": "Visionner le résultat avec un service de carte",
  "drawOnMap": "Dessin interactif sur la carte",
  "selectLayer": "Sélection d’une couche sur la carte",
  "shareResults": "Ajouter le résultat en tant que couche opérationnelle",
  "setTask": "Définir",
  "setTaskTitle": "Définir une tâche de géotraitement",
  "enablePopup": "Activer la fenêtre contextuelle",
  "unSupportGeometryType": "Impossible de définir le moteur de rendu, car le type de géométrie est inconnu.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Télécharger le fichier",
  "selectFileToUpload": "Sélectionner un fichier...",
  "rasterFormat": "Format de données raster",
  "noFileSelected": "Aucun fichier sélectionné !",
  "uploadSuccess": "Fichier chargé correctement !",
  "showLayerContent": "Afficher le contenu de la couche",
  "urlPlaceholder": "URL du jeu d'entités",
  "useShapefile": "Utiliser le format shapefile dans le système de fichiers local",
  "allowToExport": "Autoriser l'exportation des résultats",
  "useDynamicSchema": "La sortie peut avoir une structure différente. Utilisez une structure dynamique au lieu d’une structure prédéfinie.",
  "useCurrentMapExtent": "Utiliser l’étendue courante de la carte",
  "ignoreOutput": "Ignorer cette sortie",
  "turnOffOutput": "Désactiver cette couche par défaut"
});