define({
  root: ({
    showArcgisBasemaps: "Include Portal's basemaps",
    add: "Click to add a new basemap",
    edit: "Properties",
    titlePH: "Basemap title",
    thumbnailHint: "Click the image to update",
    urlPH: "Layer URL",
    addlayer: "Add basemap",
    warning: "Incorrect input",
    save: "Back and save",
    back: "Back and cancel",
    addUrl: "Add URL",
    autoCheck: "Auto check",
    checking: "Checking...",
    result: "Saved successfully",
    spError: "All basemaps added to the gallery must have the same spatial reference.",
    invalidTitle1:"A basemap '",
    invalidTitle2:"' exists already. Please choose another title.",
    invalidBasemapUrl1: "This type of layer cannot be used as a basemap.",
    invalidBasemapUrl2: "The basemap you are adding has a different spatial reference from the current map.",
    addBaselayer: "Add basemap layer",
    repectOnline: "Always synchronize with the Basemap Gallery setting of the organization",
    customBasemap: "Configure custom basemaps",
    basemapTips: "Click \"${import}\" or \"${createNew}\" to add basemaps.",
    importBasemap: "Import",
    createBasemap: "Create new",
    importTitle: "Import basemaps",
    createTitle: "New basemap",
    selectGroupTip: "Select a group whose webmaps can be used as basemaps.",
    noBasemaps: "No basemaps.",
    defaultGroup: "Esri default",
    defaultOrgGroup: "Organization default",
    warningTitle: "Warning",
    confirmDelete: "Do you want to delete selected basemaps?",
    noBasemapAvailable: "There are no basemaps available because all basemaps have different spatial reference or tiling scheme from the current map."
  }),
  "ar": 1,
  "bs": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hi": 1,
  "hr": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sl": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});