define({
  "_widgetLabel": "Geoprocessing",
  "_featureAction_ReceiveFeatureSet": "Imposta come input di ",
  "requiredInfo": "obbligatorio.",
  "drawnOnMap": "Il risultato viene disegnato nella mappa.",
  "noToolConfig": "Nessuna attività di geoprocessing preconfigurata disponibile.",
  "useUrlForGPInput": "URL",
  "useUploadForGPInput": "Carica file",
  "selectFileToUpload": "Seleziona file...",
  "rasterFormat": "Formato dati raster",
  "noFileSelected": "Nessun file selezionato.",
  "uploadSuccess": "Caricamento file riuscito.",
  "showLayerContent": "Mostra contenuto layer",
  "invalidUrl": "URL feature service non valido",
  "urlPlaceholder": "URL insieme di feature",
  "addShapefile": "Aggiungi shapefile",
  "generateShapefileError": "Genera errore shapefile. Verificare: ",
  "cleared": "Il risultato è stato cancellato.",
  "enlargeView": "Allarga vista",
  "exportOutput": "Esporta",
  "emptyResult": "Il risultato è vuoto.",
  "useSelectedFeatureset": "Utilizzare la feature o le feature risultanti.",
  "closeSelectedFeatureset": "Pulire e utilizzare l'opzione di input configurata.",
  "currentMapExtent": "Estensione mappa corrente"
});